country = {
	tag = ADE
	ai = {
		flags = { castillian = yes }
	}
	policy = {
		aristocracy = 5
		land = 5
	}
	culture = { type = madagasque type = iberian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 442 }
	ownedprovinces = { 442 }
	controlledprovinces = { 442 }
	nationalprovinces = { 441 440 443 442 }
	navalunit = {
		id = { type = 10132 id = 147 }
		name = "National Fleet"
		location = 442
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10014 id = 338 }
		name = "National Army"
		location = 442
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = AFG
	ai = {
		flags = { slavonic = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = magyar type = slavonic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 353 }
	ownedprovinces = { 353 }
	controlledprovinces = { 353 }
	nationalprovinces = { 353 352 326 325 324 354 366 367 }
	landunit = {
		id = { type = 10121 id = 590 }
		name = "National Army"
		location = 353
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = AKK
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = turkish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 473 }
	ownedprovinces = { 473 }
	controlledprovinces = { 473 }
	nationalprovinces = { 474 475 472 471 473 487 486 }
	landunit = {
		id = { type = 10137 id = 650 }
		name = "National Army"
		location = 473
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ALB
	ai = {
		flags = { slavonic = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = greek type = slavonic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 361 }
	ownedprovinces = { 361 }
	controlledprovinces = { 361 }
	nationalprovinces = { 362 363 358 359 361 394 820 }
	navalunit = {
		id = { type = 10132 id = 146 }
		name = "National Fleet"
		location = 361
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10132 id = 620 }
		name = "National Army"
		location = 361
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ALD
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = berber }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 737 }
	ownedprovinces = { 737 }
	controlledprovinces = { 737 }
	nationalprovinces = { 734 736 737 738 821 }
	navalunit = {
		id = { type = 10004 id = 483 }
		name = "National Fleet"
		location = 737
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 484 }
		name = "National Army"
		location = 737
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ALE
	ai = {
		flags = { turkish = yes arabic = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = armenian type = turkish type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 485 }
	ownedprovinces = { 485 }
	controlledprovinces = { 485 }
	nationalprovinces = { 483 474 486 485 484 490 491 492 }
	landunit = {
		id = { type = 10004 id = 2013 }
		name = "National Army"
		location = 485
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ALI
	ai = {
		flags = { armenian = yes turkish = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = albanian type = armenian type = turkish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 471 }
	ownedprovinces = { 471 }
	controlledprovinces = { 471 }
	nationalprovinces = { 471 470 468 457 487 473 472 }
	landunit = {
		id = { type = 10163 id = 656 }
		name = "National Army"
		location = 471
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ALM
	ai = {
		flags = { ruthenian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = russian type = ruthenian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 452 }
	ownedprovinces = { 452 }
	controlledprovinces = { 452 }
	nationalprovinces = { 448 447 453 451 449 452 }
	landunit = {
		id = { type = 10213 id = 988 }
		name = "National Army"
		location = 452
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ALT
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 465 }
	ownedprovinces = { 465 }
	controlledprovinces = { 465 }
	nationalprovinces = { 463 464 465 466 469 }
	navalunit = {
		id = { type = 10214 id = 180 }
		name = "National Fleet"
		location = 465
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10214 id = 666 }
		name = "National Army"
		location = 465
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = AMG
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 252 }
	ownedprovinces = { 252 }
	controlledprovinces = { 252 }
	nationalprovinces = { 251 252 253 254 308 }
	navalunit = {
		id = { type = 10004 id = 1025 }
		name = "National Fleet"
		location = 252
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2025 }
		name = "National Army"
		location = 252
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = AMI
	ai = {
		flags = { baltic = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ruthenian type = baltic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 287 }
	ownedprovinces = { 287 }
	controlledprovinces = { 287 }
	nationalprovinces = { 293 288 285 450 294 287 284 286 }
	landunit = {
		id = { type = 10216 id = 970 }
		name = "National Army"
		location = 287
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ANH
	ai = {
		flags = { lower = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = german  type = senegambian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 332 }
	ownedprovinces = { 332 }
	controlledprovinces = { 332 }
	nationalprovinces = { 333 310 311 331 347 332 }
	landunit = {
		id = { type = 10030 id = 498 }
		name = "National Army"
		location = 332
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ANJ
	ai = {
		flags = { gaelic = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = french type = gaelic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 412 }
	ownedprovinces = { 412 }
	controlledprovinces = { 412 }
	nationalprovinces = { 413 411 410 417 416 414 412 }
	landunit = {
		id = { type = 10144 id = 414 }
		name = "National Army"
		location = 412
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ANN
	ai = {
		flags = { portuguese = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = iberian type = madagasque }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 440 }
	ownedprovinces = { 440 }
	controlledprovinces = { 440 }
	nationalprovinces = { 443 442 441 434 435 436 439 440 }
	landunit = {
		id = { type = 10176 id = 352 }
		name = "National Army"
		location = 440
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = APA
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 253 }
	ownedprovinces = { 253 }
	controlledprovinces = { 253 }
	nationalprovinces = { 253 309 256 255 257 254 252 251 }
	navalunit = {
		id = { type = 10004 id = 1022 }
		name = "National Fleet"
		location = 253
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2022 }
		name = "National Army"
		location = 253
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = APU
	ai = {
		flags = { greek = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = italian type = greek }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 394 }
	ownedprovinces = { 394 }
	controlledprovinces = { 394 }
	nationalprovinces = { 394 393 395 361 362 820 359 }
	navalunit = {
		id = { type = 10146 id = 134 }
		name = "National Fleet"
		location = 394
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10146 id = 376 }
		name = "National Army"
		location = 394
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = AQU
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ashanti }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 423 }
	ownedprovinces = { 423 }
	controlledprovinces = { 423 }
	nationalprovinces = { 424 418 419 420 421 422 426 423 }
	landunit = {
		id = { type = 10106 id = 400 }
		name = "National Army"
		location = 423
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ARA
	ai = {
		flags = { egyptian = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = arabic type = nubian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 496 }
	ownedprovinces = { 496 }
	controlledprovinces = { 496 }
	nationalprovinces = { 496 494 495 489 747 746 497 749 750 }
	landunit = {
		id = { type = 10004 id = 515 }
		name = "National Army"
		location = 496
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ARG
	ai = {
		flags = { castillian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = cambodian type = iberian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 430 }
	ownedprovinces = { 430 }
	controlledprovinces = { 430 }
	nationalprovinces = { 436 437 429 427 430 435 431 428 }
	landunit = {
		id = { type = 10087 id = 368 }
		name = "National Army"
		location = 430
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ARK
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ruthenian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 462 }
	ownedprovinces = { 462 }
	controlledprovinces = { 462 }
	nationalprovinces = { 296 295 461 460 463 462 }
	landunit = {
		id = { type = 10219 id = 203 }
		name = "National Army"
		location = 462
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ARM
	ai = {
		flags = { turkish = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = armenian type = turkish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 472 }
	ownedprovinces = { 472 }
	controlledprovinces = { 472 }
	nationalprovinces = { 475 471 472 473 470 }
	landunit = {
		id = { type = 10133 id = 652 }
		name = "National Army"
		location = 472
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ART
	ai = {
		flags = { dutch = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = french type = dutch }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 379 }
	ownedprovinces = { 379 }
	controlledprovinces = { 379 }
	nationalprovinces = { 383 380 377 376 379 378 385 }
	landunit = {
		id = { type = 10186 id = 452 }
		name = "National Army"
		location = 379
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ASH
	ai = {
		flags = { magyar = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = slavonic type = magyar }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 367 }
	ownedprovinces = { 367 }
	controlledprovinces = { 367 }
	nationalprovinces = { 369 352 366 368 367 353 }
	landunit = {
		id = { type = 10166 id = 532 }
		name = "National Army"
		location = 367
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ASS
	ai = {
		flags = { franco = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = abenaki type = baluchi }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 388 }
	ownedprovinces = { 388 }
	controlledprovinces = { 388 }
	nationalprovinces = { 387 374 373 1612 404 388 405 }
	landunit = {
		id = { type = 10173 id = 508 }
		name = "National Army"
		location = 388
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = AST
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 457 }
	ownedprovinces = { 457 }
	controlledprovinces = { 457 }
	nationalprovinces = { 471 468 458 455 456 457 }
	landunit = {
		id = { type = 10004 id = 2012 }
		name = "National Army"
		location = 457
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ASU
	ai = {
		flags = { ugric = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = russian type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 268 }
	ownedprovinces = { 268 }
	controlledprovinces = { 268 }
	nationalprovinces = { 270 274 267 268 269 271 }
	landunit = {
		id = { type = 10075 id = 980 }
		name = "National Army"
		location = 268
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ATH
	policy = {
		aristocracy = 2
		land = 2
	}
	culture = { type = greek }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 360 }
	ownedprovinces = { 360 }
	controlledprovinces = { 360 }
	nationalprovinces = { 360 359 820 480 481 }
	navalunit = {
		id = { type = 10188 id = 152 }
		name = "National Fleet"
		location = 360
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10188 id = 616 }
		name = "National Army"
		location = 360
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ATJ
	policy = {
		aristocracy = 4
		land = 4
	}
	culture = { type = berber }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 445 }
	ownedprovinces = { 445 }
	controlledprovinces = { 445 }
	nationalprovinces = { 443 444 445 732 }
	navalunit = {
		id = { type = 10184 id = 302 }
		name = "National Fleet"
		location = 445
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10184 id = 356 }
		name = "National Army"
		location = 445
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = AUV
	ai = {
		flags = { franco = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ashanti type = baluchi }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 420 }
	ownedprovinces = { 420 }
	controlledprovinces = { 420 }
	nationalprovinces = { 423 421 408 409 410 419 420 }
	landunit = {
		id = { type = 10110 id = 404 }
		name = "National Army"
		location = 420
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = AYU
	ai = {
		flags = { catalan = yes occitan = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = iberian type = cambodian type = ashanti }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 431 }
	ownedprovinces = { 431 }
	controlledprovinces = { 431 }
	nationalprovinces = { 432 435 430 431 425 428 418 424 }
	navalunit = {
		id = { type = 10047 id = 118 }
		name = "National Fleet"
		location = 431
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10174 id = 350 }
		name = "National Army"
		location = 431
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = AYY
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ruthenian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 461 }
	ownedprovinces = { 461 }
	controlledprovinces = { 461 }
	nationalprovinces = { 461 450 460 462 295 }
	landunit = {
		id = { type = 10220 id = 204 }
		name = "National Army"
		location = 461
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = AZT
	ai = {
		flags = { portuguese = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = iberian type = madagasque }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 432 }
	ownedprovinces = { 432 }
	controlledprovinces = { 432 }
	nationalprovinces = { 433 434 435 432 431 }
	landunit = {
		id = { type = 10065 id = 346 }
		name = "National Army"
		location = 432
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BAD
	ai = {
		flags = { middle = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = abenaki type = german }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 373 }
	ownedprovinces = { 373 }
	controlledprovinces = { 373 }
	nationalprovinces = { 1612 388 372 347 346 374 373 }
	landunit = {
		id = { type = 10018 id = 504 }
		name = "National Army"
		location = 373
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BAE
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 454 }
	ownedprovinces = { 454 }
	controlledprovinces = { 454 }
	nationalprovinces = { 446 453 458 455 454 }
	landunit = {
		id = { type = 10004 id = 2010 }
		name = "National Army"
		location = 454
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BAL
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 466 }
	ownedprovinces = { 466 }
	controlledprovinces = { 466 }
	nationalprovinces = { 463 459 467 468 469 465 466 464 }
	navalunit = {
		id = { type = 10221 id = 178 }
		name = "National Fleet"
		location = 466
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10221 id = 664 }
		name = "National Army"
		location = 466
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BAN
	policy = {
		aristocracy = 4
		land = 4
	}
	culture = { type = madagasque }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 433 }
	ownedprovinces = { 433 }
	controlledprovinces = { 433 }
	nationalprovinces = { 434 433 432 }
	navalunit = {
		id = { type = 10076 id = 94 }
		name = "National Fleet"
		location = 433
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10076 id = 344 }
		name = "National Army"
		location = 433
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BAS
	ai = {
		flags = { armenian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = albanian type = armenian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 468 }
	ownedprovinces = { 468 }
	controlledprovinces = { 468 }
	nationalprovinces = { 466 467 458 457 471 470 469 468 }
	landunit = {
		id = { type = 10222 id = 658 }
		name = "National Army"
		location = 468
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BAY
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = abenaki }
	colonialattempts = 10
	colonialnation = no
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 349 }
	ownedprovinces = { 349 }
	controlledprovinces = { 349 }
	nationalprovinces = { 349 348 350 371 372 }
	landunit = {
		id = { type = 10019 id = 524 }
		name = "National Army"
		location = 349
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BEA
	ai = {
		flags = { catalan = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = ashanti type = cambodian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 425 }
	ownedprovinces = { 425 }
	controlledprovinces = { 425 }
	nationalprovinces = { 431 428 427 426 424 425 418 }
	landunit = {
		id = { type = 10134 id = 392 }
		name = "National Army"
		location = 425
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BEI
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ashanti }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 421 }
	ownedprovinces = { 421 }
	controlledprovinces = { 421 }
	nationalprovinces = { 421 423 420 408 422 }
	landunit = {
		id = { type = 10211 id = 402 }
		name = "National Army"
		location = 421
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BEN
	ai = {
		flags = { catalan = yes }
	}
	policy = {
		aristocracy = 5
		land = 5
	}
	culture = { type = berber type = cambodian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 438 }
	ownedprovinces = { 438 }
	controlledprovinces = { 438 }
	nationalprovinces = { 444 439 438 437 821 733 734 }
	navalunit = {
		id = { type = 10161 id = 303 }
		name = "National Fleet"
		location = 438
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10161 id = 362 }
		name = "National Army"
		location = 438
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BGL
	ai = {
		flags = { russian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ruthenian type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 449 }
	ownedprovinces = { 449 }
	controlledprovinces = { 449 }
	nationalprovinces = { 286 279 448 451 450 449 452 }
	landunit = {
		id = { type = 10223 id = 992 }
		name = "National Army"
		location = 449
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BOH
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = czech }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 328 }
	ownedprovinces = { 328 }
	controlledprovinces = { 328 }
	nationalprovinces = { 327 330 329 315 328 }
	landunit = {
		id = { type = 10021 id = 548 }
		name = "National Army"
		location = 328
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BOS
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = slavonic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 364 }
	ownedprovinces = { 364 }
	controlledprovinces = { 364 }
	nationalprovinces = { 365 366 355 363 362 364 }
	landunit = {
		id = { type = 10131 id = 608 }
		name = "National Army"
		location = 364
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BOU
	ai = {
		flags = { occitan = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = french type = ashanti }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 410 }
	ownedprovinces = { 410 }
	controlledprovinces = { 410 }
	nationalprovinces = { 419 418 417 412 411 409 420 410 }
	landunit = {
		id = { type = 10107 id = 412 }
		name = "National Army"
		location = 410
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BRA
	ai = {
		flags = { czech = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = senegambian type = czech }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 312 }
	ownedprovinces = { 312 }
	controlledprovinces = { 312 }
	nationalprovinces = { 311 304 302 313 314 329 331 312 }
	landunit = {
		id = { type = 10083 id = 494 }
		name = "National Army"
		location = 312
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BRE
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = senegambian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 336 }
	ownedprovinces = { 336 }
	controlledprovinces = { 336 }
	nationalprovinces = { 335 310 305 306 336 }
	navalunit = {
		id = { type = 10095 id = 34 }
		name = "National Fleet"
		location = 336
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10095 id = 482 }
		name = "National Army"
		location = 336
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BRI
	policy = {
		aristocracy = 4
		land = 4
	}
	culture = { type = gaelic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 415 }
	ownedprovinces = { 415 }
	controlledprovinces = { 415 }
	nationalprovinces = { 415 414 416 249 413 }
	navalunit = {
		id = { type = 10088 id = 52 }
		name = "National Fleet"
		location = 415
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10088 id = 418 }
		name = "National Army"
		location = 415
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BRZ
	ai = {
		flags = { occitan = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = cambodian type = ashanti }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 427 }
	ownedprovinces = { 427 }
	controlledprovinces = { 427 }
	nationalprovinces = { 430 428 429 425 426 427 422 821 }
	landunit = {
		id = { type = 10156 id = 374 }
		name = "National Army"
		location = 427
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BUK
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 467 }
	ownedprovinces = { 467 }
	controlledprovinces = { 467 }
	nationalprovinces = { 466 459 458 467 468 }
	landunit = {
		id = { type = 10224 id = 662 }
		name = "National Army"
		location = 467
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BUL
	ai = {
		flags = { greek = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = slavonic type = greek }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 356 }
	ownedprovinces = { 356 }
	controlledprovinces = { 356 }
	nationalprovinces = { 363 355 322 321 358 356 357 }
	landunit = {
		id = { type = 10130 id = 624 }
		name = "National Army"
		location = 356
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BUR
	ai = {
		flags = { french = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = baluchi type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 409 }
	ownedprovinces = { 409 }
	controlledprovinces = { 409 }
	nationalprovinces = { 410 411 409 386 387 408 420 }
	landunit = {
		id = { type = 10089 id = 426 }
		name = "National Army"
		location = 409
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = BYZ
	ai = {
		flags = { slavonic = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = greek type = slavonic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 357 }
	ownedprovinces = { 357 }
	controlledprovinces = { 357 }
	nationalprovinces = { 357 477 478 358 356 321 }
	navalunit = {
		id = { type = 10126 id = 168 }
		name = "National Fleet"
		location = 357
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10126 id = 628 }
		name = "National Army"
		location = 357
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CAL
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = turkish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 476 }
	ownedprovinces = { 476 }
	controlledprovinces = { 476 }
	nationalprovinces = { 482 477 1609 475 474 483 476 }
	landunit = {
		id = { type = 10140 id = 642 }
		name = "National Army"
		location = 476
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CAM
	ai = {
		flags = { catalan = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = ashanti type = cambodian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 426 }
	ownedprovinces = { 426 }
	controlledprovinces = { 426 }
	nationalprovinces = { 425 427 422 423 424 426 821 }
	landunit = {
		id = { type = 10183 id = 394 }
		name = "National Army"
		location = 426
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CAN
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = turkish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 1609 }
	ownedprovinces = { 1609 }
	controlledprovinces = { 1609 }
	nationalprovinces = { 477 476 475 1609 }
	landunit = {
		id = { type = 10191 id = 644 }
		name = "National Army"
		location = 1609
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CAT
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = cambodian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 429 }
	ownedprovinces = { 429 }
	controlledprovinces = { 429 }
	nationalprovinces = { 437 430 429 427 821 }
	navalunit = {
		id = { type = 10072 id = 108 }
		name = "National Fleet"
		location = 429
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10072 id = 370 }
		name = "National Army"
		location = 429
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CHA
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = ashanti }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 424 }
	ownedprovinces = { 424 }
	controlledprovinces = { 424 }
	nationalprovinces = { 425 426 423 424 418 431 }
	navalunit = {
		id = { type = 10201 id = 60 }
		name = "National Fleet"
		location = 424
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10201 id = 396 }
		name = "National Army"
		location = 424
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CHE
	ai = {
		flags = { tatar = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ruthenian type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 460 }
	ownedprovinces = { 460 }
	controlledprovinces = { 460 }
	nationalprovinces = { 461 451 459 463 462 460 450 }
	landunit = {
		id = { type = 10225 id = 205 }
		name = "National Army"
		location = 460
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CHG
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ashanti }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 419 }
	ownedprovinces = { 419 }
	controlledprovinces = { 419 }
	nationalprovinces = { 418 410 420 423 419 }
	landunit = {
		id = { type = 10208 id = 406 }
		name = "National Army"
		location = 419
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CHI
	ai = {
		flags = { occitan = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = baluchi type = ashanti }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 408 }
	ownedprovinces = { 408 }
	controlledprovinces = { 408 }
	nationalprovinces = { 420 409 387 405 407 422 421 408 }
	landunit = {
		id = { type = 10062 id = 428 }
		name = "National Army"
		location = 408
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CHM
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 458 }
	ownedprovinces = { 458 }
	controlledprovinces = { 458 }
	nationalprovinces = { 467 468 457 455 458 454 453 459 }
	landunit = {
		id = { type = 10226 id = 206 }
		name = "National Army"
		location = 458
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CMG
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 376 }
	ownedprovinces = { 376 }
	controlledprovinces = { 376 }
	nationalprovinces = { 385 379 377 375 386 376 }
	landunit = {
		id = { type = 10066 id = 442 }
		name = "National Army"
		location = 376
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CNW
	ai = {
		flags = { gaelic = yes }
	}
	policy = {
		aristocracy = 5
		land = 5
	}
	culture = { type = anglosaxon type = gaelic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 250 }
	ownedprovinces = { 250 }
	controlledprovinces = { 250 }
	nationalprovinces = { 250 246 249 243 234 233 }
	navalunit = {
		id = { type = 10196 id = 86 }
		name = "National Fleet"
		location = 250
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10196 id = 316 }
		name = "National Army"
		location = 250
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = COI
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 272 }
	ownedprovinces = { 272 }
	controlledprovinces = { 272 }
	nationalprovinces = { 270 271 446 447 448 272 }
	landunit = {
		id = { type = 10227 id = 982 }
		name = "National Army"
		location = 272
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = COL
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 417 }
	ownedprovinces = { 417 }
	controlledprovinces = { 417 }
	nationalprovinces = { 416 412 410 418 417 }
	navalunit = {
		id = { type = 10154 id = 56 }
		name = "National Fleet"
		location = 417
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10154 id = 410 }
		name = "National Army"
		location = 417
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CON
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = gaelic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 231 }
	ownedprovinces = { 231 }
	controlledprovinces = { 231 }
	nationalprovinces = { 235 231 233 234 232 }
	landunit = {
		id = { type = 10148 id = 186 }
		name = "National Army"
		location = 231
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = COR
	ai = {
		flags = { italian = yes }
	}
	policy = {
		aristocracy = 1
		land = 1
	}
	culture = { type = laotian type = italian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 398 }
	ownedprovinces = { 398 }
	controlledprovinces = { 398 }
	nationalprovinces = { 398 397 406 404 403 402 401 400 399 }
	navalunit = {
		id = { type = 10069 id = 122 }
		name = "National Fleet"
		location = 398
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10069 id = 320 }
		name = "National Army"
		location = 398
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CRD
	ai = {
		flags = { berber = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = iberian type = berber }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 443 }
	ownedprovinces = { 443 }
	controlledprovinces = { 443 }
	nationalprovinces = { 442 440 439 443 444 445 }
	navalunit = {
		id = { type = 10015 id = 100 }
		name = "National Fleet"
		location = 443
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10015 id = 354 }
		name = "National Army"
		location = 443
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CRE
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ruthenian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 450 }
	ownedprovinces = { 450 }
	controlledprovinces = { 450 }
	nationalprovinces = { 287 286 449 451 460 461 295 450 294 }
	landunit = {
		id = { type = 10217 id = 996 }
		name = "National Army"
		location = 450
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CRG
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ruthenian type = baltic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 294 }
	ownedprovinces = { 294 }
	controlledprovinces = { 294 }
	nationalprovinces = { 293 287 450 295 297 294 }
	landunit = {
		id = { type = 10218 id = 998 }
		name = "National Army"
		location = 294
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CRI
	ai = {
		flags = { ruthenian = yes romanian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = albanian type = ruthenian type = romanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 463 }
	ownedprovinces = { 463 }
	controlledprovinces = { 463 }
	nationalprovinces = { 463 464 465 466 459 460 462 296 319 }
	navalunit = {
		id = { type = 10023 id = 174 }
		name = "National Fleet"
		location = 463
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10023 id = 201 }
		name = "National Army"
		location = 463
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CRO
	ai = {
		flags = { magyar = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = slavonic type = magyar }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 366 }
	ownedprovinces = { 366 }
	controlledprovinces = { 366 }
	nationalprovinces = { 367 353 354 355 364 365 368 366 }
	landunit = {
		id = { type = 10193 id = 604 }
		name = "National Army"
		location = 366
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CUM
	ai = {
		flags = { tatar = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ruthenian type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 451 }
	ownedprovinces = { 451 }
	controlledprovinces = { 451 }
	nationalprovinces = { 449 452 453 459 460 450 451 }
	landunit = {
		id = { type = 10228 id = 994 }
		name = "National Army"
		location = 451
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CYP
	ai = {
		flags = { turkish = yes arabic = yes }
	}
	policy = {
		aristocracy = 0
		land = 0
	}
	culture = { type = greek type = turkish type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 484 }
	ownedprovinces = { 484 }
	controlledprovinces = { 484 }
	nationalprovinces = { 484 1610 1611 483 485 491 492 493 494 }
	navalunit = {
		id = { type = 10004 id = 1019 }
		name = "National Fleet"
		location = 484
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2019 }
		name = "National Army"
		location = 484
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = CYR
	ai = {
		flags = { greek = yes }
	}
	policy = {
		aristocracy = 5
		land = 5
	}
	culture = { type = nubian type = greek }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 741 }
	ownedprovinces = { 741 }
	controlledprovinces = { 741 }
	nationalprovinces = { 480 741 740 742 819 820 }
	navalunit = {
		id = { type = 10004 id = 491 }
		name = "National Fleet"
		location = 741
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 492 }
		name = "National Army"
		location = 741
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = DAH
	policy = {
		aristocracy = 4
		land = 4
	}
	culture = { type = italian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 395 }
	ownedprovinces = { 395 }
	controlledprovinces = { 395 }
	nationalprovinces = { 395 396 394 819 397 }
	navalunit = {
		id = { type = 10165 id = 132 }
		name = "National Fleet"
		location = 395
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10165 id = 328 }
		name = "National Army"
		location = 395
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = DAI
	ai = {
		flags = { romanian = yes }
	}
	policy = {
		aristocracy = 5
		land = 5
	}
	culture = { type = albanian type = romanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 464 }
	ownedprovinces = { 464 }
	controlledprovinces = { 464 }
	nationalprovinces = { 464 463 465 319 296 466 }
	navalunit = {
		id = { type = 10229 id = 176 }
		name = "National Fleet"
		location = 464
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10229 id = 207 }
		name = "National Army"
		location = 464
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = DAK
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ruthenian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 286 }
	ownedprovinces = { 286 }
	controlledprovinces = { 286 }
	nationalprovinces = { 285 449 450 287 286 279 }
	landunit = {
		id = { type = 10230 id = 974 }
		name = "National Army"
		location = 286
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = DAM
	ai = {
		flags = { ruthenian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = albanian type = ruthenian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 459 }
	ownedprovinces = { 459 }
	controlledprovinces = { 459 }
	nationalprovinces = { 466 463 460 451 453 458 467 459 }
	landunit = {
		id = { type = 10231 id = 208 }
		name = "National Army"
		location = 459
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = DAN
	ai = {
		flags = { lower = yes }
	}
	policy = {
		aristocracy = 4
		land = 4
	}
	culture = { type = scandinavian type = senegambian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 307 }
	ownedprovinces = { 307 }
	controlledprovinces = { 307 }
	nationalprovinces = { 307 309 306 305 304 251 }
	navalunit = {
		id = { type = 10004 id = 1002 }
		name = "National Fleet"
		location = 307
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2002 }
		name = "National Army"
		location = 307
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = DAU
	ai = {
		flags = { occitan = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = baluchi type = ashanti }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 407 }
	ownedprovinces = { 407 }
	controlledprovinces = { 407 }
	nationalprovinces = { 422 406 405 408 407 }
	landunit = {
		id = { type = 10157 id = 430 }
		name = "National Army"
		location = 407
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = DEL
	ai = {
		flags = { russian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = albanian type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 453 }
	ownedprovinces = { 453 }
	controlledprovinces = { 453 }
	nationalprovinces = { 451 459 458 454 453 446 447 452 }
	landunit = {
		id = { type = 10232 id = 990 }
		name = "National Army"
		location = 453
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = DLH
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 447 }
	ownedprovinces = { 447 }
	controlledprovinces = { 447 }
	nationalprovinces = { 272 448 447 452 453 446 }
	landunit = {
		id = { type = 10035 id = 986 }
		name = "National Army"
		location = 447
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = DUL
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = turkish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 474 }
	ownedprovinces = { 474 }
	controlledprovinces = { 474 }
	nationalprovinces = { 483 485 486 473 475 476 474 }
	landunit = {
		id = { type = 10190 id = 648 }
		name = "National Army"
		location = 474
		morale = 2
		inf = 5000
		cav = 5000
	}
}
		

country = {
	tag = EDE
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = turkish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 486 }
	ownedprovinces = { 486 }
	controlledprovinces = { 486 }
	nationalprovinces = { 473 474 486 487 485 490 }
	landunit = {
		id = { type = 10004 id = 2020 }
		name = "National Army"
		location = 486
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = EGY
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 255 }
	ownedprovinces = { 255 }
	controlledprovinces = { 255 }
	nationalprovinces = { 309 253 255 257 381 258 256 }
	navalunit = {
		id = { type = 10004 id = 1034 }
		name = "National Fleet"
		location = 255
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2034 }
		name = "National Army"
		location = 255
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = EIR
	ai = {
		flags = { french = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = gaelic type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 416 }
	ownedprovinces = { 416 }
	controlledprovinces = { 416 }
	nationalprovinces = { 417 412 416 415 414 }
	navalunit = {
		id = { type = 10187 id = 54 }
		name = "National Fleet"
		location = 416
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10187 id = 416 }
		name = "National Army"
		location = 416
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ENG
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = anglosaxon }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 247 }
	ownedprovinces = { 247 }
	controlledprovinces = { 247 }
	nationalprovinces = { 248 249 246 245 247 }
	navalunit = {
		id = { type = 10004 id = 80 }
		name = "National Fleet"
		location = 247
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 308 }
		name = "National Army"
		location = 247
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ETH
	ai = {
		flags = { french = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = gaelic type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 414 }
	ownedprovinces = { 414 }
	controlledprovinces = { 414 }
	nationalprovinces = { 414 415 416 412 413 249 }
	navalunit = {
		id = { type = 10158 id = 50 }
		name = "National Fleet"
		location = 414
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10158 id = 420 }
		name = "National Army"
		location = 414
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = FAT
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 256 }
	ownedprovinces = { 256 }
	controlledprovinces = { 256 }
	nationalprovinces = { 258 255 256 309 253 }
	navalunit = {
		id = { type = 10004 id = 1023 }
		name = "National Fleet"
		location = 256
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2023 }
		name = "National Army"
		location = 256
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = FEZ
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = berber }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 733 }
	ownedprovinces = { 733 }
	controlledprovinces = { 733 }
	nationalprovinces = { 732 733 444 438 734 735 821 806 }
	landunit = {
		id = { type = 10004 id = 478 }
		name = "National Army"
		location = 733
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = FLA
	ai = {
		flags = { french = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = dutch type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 380 }
	ownedprovinces = { 380 }
	controlledprovinces = { 380 }
	nationalprovinces = { 382 383 379 378 340 380 339 338 337 }
	navalunit = {
		id = { type = 10099 id = 42 }
		name = "National Fleet"
		location = 380
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10099 id = 454 }
		name = "National Army"
		location = 380
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = FPR
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 258 }
	ownedprovinces = { 258 }
	controlledprovinces = { 258 }
	nationalprovinces = { 256 255 258 381 259 }
	navalunit = {
		id = { type = 10004 id = 1024 }
		name = "National Fleet"
		location = 258
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2024 }
		name = "National Army"
		location = 258
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = FRC
	ai = {
		flags = { ugric = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = scandinavian type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 259 }
	ownedprovinces = { 259 }
	controlledprovinces = { 259 }
	nationalprovinces = { 258 381 259 260 261 263 }
	navalunit = {
		id = { type = 10004 id = 1004 }
		name = "National Fleet"
		location = 259
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2004 }
		name = "National Army"
		location = 259
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = FRI
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = dutch }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 337 }
	ownedprovinces = { 337 }
	controlledprovinces = { 337 }
	nationalprovinces = { 339 338 337 380 340 335 }
	landunit = {
		id = { type = 10098 id = 464 }
		name = "National Army"
		location = 337
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = FUC
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = berber }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 735 }
	ownedprovinces = { 735 }
	controlledprovinces = { 735 }
	nationalprovinces = { 733 735 734 736 }
	landunit = {
		id = { type = 10004 id = 481 }
		name = "National Army"
		location = 735
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = GEL
	ai = {
		flags = { lower = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = dutch type = senegambian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 338 }
	ownedprovinces = { 338 }
	controlledprovinces = { 338 }
	nationalprovinces = { 340 339 337 335 334 338 380 }
	navalunit = {
		id = { type = 10097 id = 36 }
		name = "National Fleet"
		location = 338
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10097 id = 460 }
		name = "National Army"
		location = 338
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = GEN
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = laotian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 403 }
	ownedprovinces = { 403 }
	controlledprovinces = { 403 }
	nationalprovinces = { 403 404 389 402 398 401 397 }
	navalunit = {
		id = { type = 10026 id = 116 }
		name = "National Fleet"
		location = 403
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10026 id = 516 }
		name = "National Army"
		location = 403
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = GEO
	ai = {
		flags = { tatar = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = armenian type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 470 }
	ownedprovinces = { 470 }
	controlledprovinces = { 470 }
	nationalprovinces = { 469 468 471 470 472 475 }
	landunit = {
		id = { type = 10082 id = 654 }
		name = "National Army"
		location = 470
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = GOT
	policy = {
		aristocracy = 0
		land = 0
	}
	culture = { type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 308 }
	ownedprovinces = { 308 }
	controlledprovinces = { 308 }
	nationalprovinces = { 308 251 252 254 }
	navalunit = {
		id = { type = 10004 id = 1033 }
		name = "National Fleet"
		location = 308
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2033 }
		name = "National Army"
		location = 308
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = GRA
	ai = {
		flags = { castillian = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = berber type = iberian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 444 }
	ownedprovinces = { 444 }
	controlledprovinces = { 444 }
	nationalprovinces = { 445 443 444 439 438 821 733 734 }
	landunit = {
		id = { type = 10093 id = 358 }
		name = "National Army"
		location = 444
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = GRE
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = greek }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 359 }
	ownedprovinces = { 359 }
	controlledprovinces = { 359 }
	nationalprovinces = { 361 358 359 360 479 478 362 820 481 394 480 }
	navalunit = {
		id = { type = 10128 id = 150 }
		name = "National Fleet"
		location = 359
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10128 id = 618 }
		name = "National Army"
		location = 359
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = GUJ
	ai = {
		flags = { ugric = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = scandinavian type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 1469 }
	ownedprovinces = { 1469 }
	controlledprovinces = { 1469 }
	nationalprovinces = { 254 257 1469 381 341 260 263 342 }
	navalunit = {
		id = { type = 10004 id = 1031 }
		name = "National Fleet"
		location = 1469
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2031 }
		name = "National Army"
		location = 1469
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = HAI
	policy = {
		aristocracy = 1
		land = 1
	}
	culture = { type = greek }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 820 }
	ownedprovinces = { 820 }
	controlledprovinces = { 820 }
	nationalprovinces = { 360 359 480 820 394 361 362 741 }
	navalunit = {
		id = { type = 10150 id = 148 }
		name = "National Fleet"
		location = 820
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10150 id = 330 }
		name = "National Army"
		location = 820
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = HAM
	ai = {
		flags = { scandinavian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ugric type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 260 }
	ownedprovinces = { 260 }
	controlledprovinces = { 260 }
	nationalprovinces = { 381 1469 260 341 263 259 }
	landunit = {
		id = { type = 10004 id = 2035 }
		name = "National Army"
		location = 260
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = HAN
	ai = {
		flags = { middle = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = senegambian type = german }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 310 }
	ownedprovinces = { 310 }
	controlledprovinces = { 310 }
	nationalprovinces = { 333 334 335 336 305 311 332 310 }
	landunit = {
		id = { type = 10027 id = 486 }
		name = "National Army"
		location = 310
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = HAU
	ai = {
		flags = { german = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = dutch type = german }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 378 }
	ownedprovinces = { 378 }
	controlledprovinces = { 378 }
	nationalprovinces = { 379 380 340 344 377 378 }
	landunit = {
		id = { type = 10109 id = 456 }
		name = "National Army"
		location = 378
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = HEI
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 261 }
	ownedprovinces = { 261 }
	controlledprovinces = { 261 }
	nationalprovinces = { 261 262 259 263 }
	navalunit = {
		id = { type = 10004 id = 1017 }
		name = "National Fleet"
		location = 261
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2017 }
		name = "National Army"
		location = 261
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = HEL
	ai = {
		flags = { umbrian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = abenaki type = laotian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 1612 }
	ownedprovinces = { 1612 }
	controlledprovinces = { 1612 }
	nationalprovinces = { 388 373 372 371 1612 389 404 }
	landunit = {
		id = { type = 10029 id = 510 }
		name = "National Army"
		location = 1612
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = HES
	ai = {
		flags = { lower = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = german type = senegambian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 333 }
	ownedprovinces = { 333 }
	controlledprovinces = { 333 }
	nationalprovinces = { 343 334 310 332 347 346 345 333 }
	landunit = {
		id = { type = 10031 id = 488 }
		name = "National Army"
		location = 333
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = HLL
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = dutch }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 339 }
	ownedprovinces = { 339 }
	controlledprovinces = { 339 }
	nationalprovinces = { 340 338 337 339 380 }
	navalunit = {
		id = { type = 10004 id = 38 }
		name = "National Fleet"
		location = 339
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 462 }
		name = "National Army"
		location = 339
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = HSA
	ai = {
		flags = { ugric = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = scandinavian type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 341 }
	ownedprovinces = { 341 }
	controlledprovinces = { 341 }
	nationalprovinces = { 1469 341 342 263 260 }
	navalunit = {
		id = { type = 10004 id = 1001 }
		name = "National Fleet"
		location = 341
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2001 }
		name = "National Army"
		location = 341
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = HUR
	ai = {
		flags = { french = yes upper = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = baluchi type = french type = abenaki }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 387 }
	ownedprovinces = { 387 }
	controlledprovinces = { 387 }
	nationalprovinces = { 408 405 388 374 375 386 409 387 }
	landunit = {
		id = { type = 10142 id = 436 }
		name = "National Army"
		location = 387
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = HYD
	ai = {
		flags = { franco = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = french  type = baluchi}
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 386 }
	ownedprovinces = { 386 }
	controlledprovinces = { 386 }
	nationalprovinces = { 411 376 375 387 409 386 385 }
	landunit = {
		id = { type = 10033 id = 438 }
		name = "National Army"
		location = 386
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ICE
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = berber }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 734 }
	ownedprovinces = { 734 }
	controlledprovinces = { 734 }
	nationalprovinces = { 733 444 445 438 735 736 737 821 }
	navalunit = {
		id = { type = 10004 id = 479 }
		name = "National Fleet"
		location = 734
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 480 }
		name = "National Army"
		location = 734
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = INC
	ai = {
		flags = { scandinavian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = ugric type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 263 }
	ownedprovinces = { 263 }
	controlledprovinces = { 263 }
	nationalprovinces = { 260 341 259 261 263 262 273 264 342 1469 }
	navalunit = {
		id = { type = 10004 id = 1032 }
		name = "National Fleet"
		location = 263
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2032 }
		name = "National Army"
		location = 263
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = IRA
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 489 }
	ownedprovinces = { 489 }
	controlledprovinces = { 489 }
	nationalprovinces = { 489 488 508 496 490 531 495 }
	landunit = {
		id = { type = 10004 id = 518 }
		name = "National Army"
		location = 489
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = IST
	ai = {
		flags = { umbrian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = slavonic type = laotian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 368 }
	ownedprovinces = { 368 }
	controlledprovinces = { 368 }
	nationalprovinces = { 365 370 369 367 366 368 390 391 392 }
	navalunit = {
		id = { type = 10198 id = 140 }
		name = "National Fleet"
		location = 368
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10198 id = 528 }
		name = "National Army"
		location = 368
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = JAI
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 381 }
	ownedprovinces = { 381 }
	controlledprovinces = { 381 }
	nationalprovinces = { 258 255 257 381 260 1469 259 }
	landunit = {
		id = { type = 10004 id = 2029 }
		name = "National Army"
		location = 381
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = JER
	ai = {
		flags = { arabic = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = turkish type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 483 }
	ownedprovinces = { 483 }
	controlledprovinces = { 483 }
	nationalprovinces = { 1611 482 476 474 485 483 484 491 492 }
	navalunit = {
		id = { type = 10194 id = 160 }
		name = "National Fleet"
		location = 483
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10194 id = 640 }
		name = "National Army"
		location = 483
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = JUT
	ai = {
		flags = { lower = yes }
	}
	policy = {
		aristocracy = 5
		land = 5
	}
	culture = { type = scandinavian type = senegambian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 309 }
	ownedprovinces = { 309 }
	controlledprovinces = { 309 }
	nationalprovinces = { 251 253 255 256 304 306 305 309 307 }
	navalunit = {
		id = { type = 10025 id = 32 }
		name = "National Fleet"
		location = 309
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10025 id = 478 }
		name = "National Army"
		location = 309
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KAR
	ai = {
		flags = { greek = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = turkish type = greek }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 1611 }
	ownedprovinces = { 1611 }
	controlledprovinces = { 1611 }
	nationalprovinces = { 1610 482 1611 483 481 484 }
	landunit = {
		id = { type = 10189 id = 638 }
		name = "National Army"
		location = 1611
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KAZ
	ai = {
		flags = { russian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = albanian type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 446 }
	ownedprovinces = { 446 }
	controlledprovinces = { 446 }
	nationalprovinces = { 271 272 447 453 446 454 }
	landunit = {
		id = { type = 10004 id = 2016 }
		name = "National Army"
		location = 446
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KHM
	ai = {
		flags = { gaelic = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = anglosaxon type = gaelic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 246 }
	ownedprovinces = { 246 }
	controlledprovinces = { 246 }
	nationalprovinces = { 243 244 245 247 249 250 246 234 233 }
	navalunit = {
		id = { type = 10182 id = 88 }
		name = "National Fleet"
		location = 246
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10182 id = 314 }
		name = "National Army"
		location = 246
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KIE
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = berber }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 736 }
	ownedprovinces = { 736 }
	controlledprovinces = { 736 }
	nationalprovinces = { 736 735 737 738 734 }
	landunit = {
		id = { type = 10004 id = 482 }
		name = "National Army"
		location = 736
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KLE
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = german }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 343 }
	ownedprovinces = { 343 }
	controlledprovinces = { 343 }
	nationalprovinces = { 340 334 333 345 344 343 }
	landunit = {
		id = { type = 10020 id = 472 }
		name = "National Army"
		location = 343
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KOL
	ai = {
		flags = { dutch = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = german type = dutch }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 344 }
	ownedprovinces = { 344 }
	controlledprovinces = { 344 }
	nationalprovinces = { 340 343 345 377 378 344 }
	landunit = {
		id = { type = 10036 id = 470 }
		name = "National Army"
		location = 344
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KON
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = anglosaxon }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 245 }
	ownedprovinces = { 245 }
	controlledprovinces = { 245 }
	nationalprovinces = { 244 241 247 246 245 240 248 }
	landunit = {
		id = { type = 10159 id = 306 }
		name = "National Army"
		location = 245
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KOR
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 264 }
	ownedprovinces = { 264 }
	controlledprovinces = { 264 }
	nationalprovinces = { 263 273 264 265 342 }
	landunit = {
		id = { type = 10004 id = 2026 }
		name = "National Army"
		location = 264
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KRE
	ai = {
		flags = { egyptian = yes }
	}
	policy = {
		aristocracy = 0
		land = 0
	}
	culture = { type = greek type = nubian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 480 }
	ownedprovinces = { 480 }
	controlledprovinces = { 480 }
	nationalprovinces = { 480 359 360 820 741 742 744 745 746 }
	navalunit = {
		id = { type = 10022 id = 154 }
		name = "National Fleet"
		location = 480
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10022 id = 332 }
		name = "National Army"
		location = 480
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KRN
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 273 }
	ownedprovinces = { 273 }
	controlledprovinces = { 273 }
	nationalprovinces = { 264 263 273 262 1470 266 265 }
	landunit = {
		id = { type = 10004 id = 2006 }
		name = "National Army"
		location = 273
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KSH
	ai = {
		flags = { polish = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = baltic type = polish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 301 }
	ownedprovinces = { 301 }
	controlledprovinces = { 301 }
	nationalprovinces = { 301 303 300 302 290 }
	navalunit = {
		id = { type = 10172 id = 22 }
		name = "National Fleet"
		location = 301
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10172 id = 562 }
		name = "National Army"
		location = 301
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KUR
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = baltic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 283 }
	ownedprovinces = { 283 }
	controlledprovinces = { 283 }
	nationalprovinces = { 289 290 288 284 281 282 283 }
	navalunit = {
		id = { type = 10092 id = 16 }
		name = "National Fleet"
		location = 283
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10092 id = 952 }
		name = "National Army"
		location = 283
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KUS
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = senegambian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 313 }
	ownedprovinces = { 313 }
	controlledprovinces = { 313 }
	nationalprovinces = { 313 312 302 303 314 }
	landunit = {
		id = { type = 10145 id = 554 }
		name = "National Army"
		location = 313
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = KZK
	ai = {
		flags = { french = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = anglosaxon type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 248 }
	ownedprovinces = { 248 }
	controlledprovinces = { 248 }
	nationalprovinces = { 249 247 248 384 382 383 245 413 }
	navalunit = {
		id = { type = 10120 id = 82 }
		name = "National Fleet"
		location = 248
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10120 id = 310 }
		name = "National Army"
		location = 248
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LAN
	ai = {
		flags = { gaelic = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = anglosaxon type = gaelic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 242 }
	ownedprovinces = { 242 }
	controlledprovinces = { 242 }
	nationalprovinces = { 243 244 242 241 240 239 232 233 237 }
	navalunit = {
		id = { type = 10167 id = 92 }
		name = "National Fleet"
		location = 242
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10167 id = 298 }
		name = "National Army"
		location = 242
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LAP
	policy = {
		aristocracy = 2
		land = 2
	}
	culture = { type = gaelic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 236 }
	ownedprovinces = { 236 }
	controlledprovinces = { 236 }
	nationalprovinces = { 237 236 }
	navalunit = {
		id = { type = 10155 id = 68 }
		name = "National Fleet"
		location = 236
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10155 id = 288 }
		name = "National Army"
		location = 236
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LAT
	ai = {
		flags = { russian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = baltic type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 282 }
	ownedprovinces = { 282 }
	controlledprovinces = { 282 }
	nationalprovinces = { 282 276 277 280 281 283 289 290 }
	navalunit = {
		id = { type = 10037 id = 14 }
		name = "National Fleet"
		location = 282
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10037 id = 954 }
		name = "National Army"
		location = 282
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LEI
	ai = {
		flags = { anglian = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = gaelic type = anglosaxon }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 234 }
	ownedprovinces = { 234 }
	controlledprovinces = { 234 }
	nationalprovinces = { 234 235 231 233 243 246 250 }
	landunit = {
		id = { type = 10070 id = 194 }
		name = "National Army"
		location = 234
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LEO
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = iberian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 435 }
	ownedprovinces = { 435 }
	controlledprovinces = { 435 }
	nationalprovinces = { 440 434 432 431 430 436 435 }
	landunit = {
		id = { type = 10181 id = 348 }
		name = "National Army"
		location = 435
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LGD
	ai = {
		flags = { magyar = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = abenaki type = magyar }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 351 }
	ownedprovinces = { 351 }
	controlledprovinces = { 351 }
	nationalprovinces = { 369 350 327 326 352 351 }
	landunit = {
		id = { type = 10004 id = 539 }
		name = "National Army"
		location = 351
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LIT
	ai = {
		flags = { polish = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = baltic type = polish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 288 }
	ownedprovinces = { 288 }
	controlledprovinces = { 288 }
	nationalprovinces = { 291 290 284 287 293 292 288 283 }
	landunit = {
		id = { type = 10114 id = 566 }
		name = "National Army"
		location = 288
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LIV
	ai = {
		flags = { scandinavian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = ugric type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 265 }
	ownedprovinces = { 265 }
	controlledprovinces = { 265 }
	nationalprovinces = { 265 276 275 266 273 264 342 254 1469 }
	navalunit = {
		id = { type = 10004 id = 1009 }
		name = "National Fleet"
		location = 265
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2009 }
		name = "National Army"
		location = 265
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LOR
	ai = {
		flags = { middle = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = french type = german }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 375 }
	ownedprovinces = { 375 }
	controlledprovinces = { 375 }
	nationalprovinces = { 374 387 386 376 377 345 375 }
	landunit = {
		id = { type = 10038 id = 440 }
		name = "National Army"
		location = 375
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LOU
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 266 }
	ownedprovinces = { 266 }
	controlledprovinces = { 266 }
	nationalprovinces = { 273 1470 266 267 275 265 }
	landunit = {
		id = { type = 10004 id = 2028 }
		name = "National Army"
		location = 266
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LUA
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 262 }
	ownedprovinces = { 262 }
	controlledprovinces = { 262 }
	nationalprovinces = { 269 267 1470 262 261 263 273 }
	navalunit = {
		id = { type = 10004 id = 1008 }
		name = "National Fleet"
		location = 262
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2008 }
		name = "National Army"
		location = 262
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = LUX
	ai = {
		flags = { french = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = german type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 377 }
	ownedprovinces = { 377 }
	controlledprovinces = { 377 }
	nationalprovinces = { 377 378 344 345 375 376 379 }
	landunit = {
		id = { type = 10108 id = 466 }
		name = "National Army"
		location = 377
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MAA
	ai = {
		flags = { upper = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = magyar type = abenaki }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 352 }
	ownedprovinces = { 352 }
	controlledprovinces = { 352 }
	nationalprovinces = { 352 351 326 353 367 369 }
	landunit = {
		id = { type = 10153 id = 534 }
		name = "National Army"
		location = 352
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MAG
	ai = {
		flags = { middle = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = senegambian type = german }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 311 }
	ownedprovinces = { 311 }
	controlledprovinces = { 311 }
	nationalprovinces = { 310 305 304 312 331 332 311 }
	landunit = {
		id = { type = 10100 id = 492 }
		name = "National Army"
		location = 311
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MAH
	ai = {
		flags = { middle = yes upper = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = czech type = german type = abenaki }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 330 }
	ownedprovinces = { 330 }
	controlledprovinces = { 330 }
	nationalprovinces = { 348 327 328 329 331 347 330 }
	landunit = {
		id = { type = 10077 id = 544 }
		name = "National Army"
		location = 330
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MAI
	ai = {
		flags = { upper = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = german type = abenaki }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 346 }
	ownedprovinces = { 346 }
	controlledprovinces = { 346 }
	nationalprovinces = { 374 345 333 347 373 346 }
	landunit = {
		id = { type = 10102 id = 502 }
		name = "National Army"
		location = 346
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MAL
	ai = {
		flags = { arabic = yes }
	}
	policy = {
		aristocracy = 0
		land = 0
	}
	culture = { type = italian type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 819 }
	ownedprovinces = { 819 }
	controlledprovinces = { 819 }
	nationalprovinces = { 395 396 819 739 740 741 }
	navalunit = {
		id = { type = 10151 id = 130 }
		name = "National Fleet"
		location = 819
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10151 id = 324 }
		name = "National Army"
		location = 819
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MAN
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = laotian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 390 }
	ownedprovinces = { 390 }
	controlledprovinces = { 390 }
	nationalprovinces = { 391 389 371 390 370 368 392 }
	landunit = {
		id = { type = 10123 id = 518 }
		name = "National Army"
		location = 390
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MCH
	ai = {
		flags = { gaelic = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = anglosaxon type = gaelic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 240 }
	ownedprovinces = { 240 }
	controlledprovinces = { 240 }
	nationalprovinces = { 238 239 240 241 242 245 237 243 233 232 }
	navalunit = {
		id = { type = 10168 id = 76 }
		name = "National Fleet"
		location = 240
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10168 id = 296 }
		name = "National Army"
		location = 240
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MEA
	ai = {
		flags = { anglian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = gaelic type = anglosaxon }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 233 }
	ownedprovinces = { 233 }
	controlledprovinces = { 233 }
	nationalprovinces = { 231 234 232 233 250 246 243 242 240 239 237 }
	navalunit = {
		id = { type = 10164 id = 64 }
		name = "National Fleet"
		location = 233
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10164 id = 190 }
		name = "National Army"
		location = 233
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MEC
	ai = {
		flags = { scandinavian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = senegambian type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 305 }
	ownedprovinces = { 305 }
	controlledprovinces = { 305 }
	nationalprovinces = { 251 311 310 336 306 304 305 307 309 }
	navalunit = {
		id = { type = 10094 id = 28 }
		name = "National Fleet"
		location = 305
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10094 id = 484 }
		name = "National Army"
		location = 305
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MES
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 1470 }
	ownedprovinces = { 1470 }
	controlledprovinces = { 1470 }
	nationalprovinces = { 262 273 266 1470 267 269 }
	landunit = {
		id = { type = 10004 id = 2030 }
		name = "National Army"
		location = 1470
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MEX
	ai = {
		flags = { russian = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = ugric type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 267 }
	ownedprovinces = { 267 }
	controlledprovinces = { 267 }
	nationalprovinces = { 1470 266 275 274 267 268 269 262 }
	landunit = {
		id = { type = 10004 id = 2007 }
		name = "National Army"
		location = 267
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MIN
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = baltic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 275 }
	ownedprovinces = { 275 }
	controlledprovinces = { 275 }
	nationalprovinces = { 265 266 267 274 275 276 277 }
	navalunit = {
		id = { type = 10004 id = 81 }
		name = "National Fleet"
		location = 275
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 309 }
		name = "National Army"
		location = 275
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MKS
	ai = {
		flags = { anglian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = gaelic type = anglosaxon }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 237 }
	ownedprovinces = { 237 }
	controlledprovinces = { 237 }
	nationalprovinces = { 236 237 239 238 243 242 233 232 240 }
	navalunit = {
		id = { type = 10212 id = 70 }
		name = "National Fleet"
		location = 237
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10212 id = 290 }
		name = "National Army"
		location = 237
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MLC
	ai = {
		flags = { ugric = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = russian type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 269 }
	ownedprovinces = { 269 }
	controlledprovinces = { 269 }
	nationalprovinces = { 267 1470 262 269 268 271 }
	navalunit = {
		id = { type = 10004 id = 1021 }
		name = "National Fleet"
		location = 269
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2021 }
		name = "National Army"
		location = 269
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MLL
	ai = {
		flags = { berber = yes occitan = yes }
	}
	policy = {
		aristocracy = 0
		land = 0
	}
	culture = { type = cambodian type = berber type = ashanti }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 821 }
	ownedprovinces = { 821 }
	controlledprovinces = { 821 }
	nationalprovinces = { 821 444 438 437 429 427 426 422 733 734 737 738 }
	navalunit = {
		id = { type = 10195 id = 112 }
		name = "National Fleet"
		location = 821
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10195 id = 318 }
		name = "National Army"
		location = 821
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MLO
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = laotian type = abenaki }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 389 }
	ownedprovinces = { 389 }
	controlledprovinces = { 389 }
	nationalprovinces = { 389 1612 371 390 402 403 404 391 }
	landunit = {
		id = { type = 10041 id = 514 }
		name = "National Army"
		location = 389
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MLW
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = gaelic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 238 }
	ownedprovinces = { 238 }
	controlledprovinces = { 238 }
	nationalprovinces = { 237 239 238 240 }
	navalunit = {
		id = { type = 10197 id = 74 }
		name = "National Fleet"
		location = 238
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10197 id = 294 }
		name = "National Army"
		location = 238
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MOG
	ai = {
		flags = { greek = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = slavonic type = greek }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 363 }
	ownedprovinces = { 363 }
	controlledprovinces = { 363 }
	nationalprovinces = { 361 362 364 355 356 363 358 }
	landunit = {
		id = { type = 10064 id = 612 }
		name = "National Army"
		location = 363
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MOL
	ai = {
		flags = { magyar = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = romanian type = magyar }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 318 }
	ownedprovinces = { 318 }
	controlledprovinces = { 318 }
	nationalprovinces = { 323 298 297 296 319 320 322 318 317 }
	landunit = {
		id = { type = 10042 id = 600 }
		name = "National Army"
		location = 318
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MOR
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = berber }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 806 }
	ownedprovinces = { 806 }
	controlledprovinces = { 806 }
	nationalprovinces = { 806 733 }
	landunit = {
		id = { type = 10004 id = 530 }
		name = "National Army"
		location = 806
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MOS
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 270 }
	ownedprovinces = { 270 }
	controlledprovinces = { 270 }
	nationalprovinces = { 279 278 274 268 271 272 448 270 }
	landunit = {
		id = { type = 10118 id = 978 }
		name = "National Army"
		location = 270
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MSK
	ai = {
		flags = { ruthenian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = baltic type = ruthenian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 284 }
	ownedprovinces = { 284 }
	controlledprovinces = { 284 }
	nationalprovinces = { 288 284 283 281 280 285 287 }
	landunit = {
		id = { type = 10054 id = 968 }
		name = "National Army"
		location = 284
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MST
	policy = {
		aristocracy = 4
		land = 4
	}
	culture = { type = gaelic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 235 }
	ownedprovinces = { 235 }
	controlledprovinces = { 235 }
	nationalprovinces = { 231 234 235 }
	navalunit = {
		id = { type = 10178 id = 66 }
		name = "National Fleet"
		location = 235
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10178 id = 192 }
		name = "National Army"
		location = 235
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MTR
	ai = {
		flags = { upper = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = czech type = abenaki }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 327 }
	ownedprovinces = { 327 }
	controlledprovinces = { 327 }
	nationalprovinces = { 348 330 328 315 326 351 350 327 }
	landunit = {
		id = { type = 10210 id = 540 }
		name = "National Army"
		location = 327
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MUN
	ai = {
		flags = { middle = yes dutch = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = senegambian type = german type = dutch }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 334 }
	ownedprovinces = { 334 }
	controlledprovinces = { 334 }
	nationalprovinces = { 338 335 310 333 343 340 334 }
	landunit = {
		id = { type = 10103 id = 474 }
		name = "National Army"
		location = 334
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MYA
	ai = {
		flags = { baltic = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = polish type = baltic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 300 }
	ownedprovinces = { 300 }
	controlledprovinces = { 300 }
	nationalprovinces = { 303 301 290 291 292 299 300 314 }
	landunit = {
		id = { type = 10179 id = 560 }
		name = "National Army"
		location = 300
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = MYS
	ai = {
		flags = { lower = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = polish type = senegambian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 303 }
	ownedprovinces = { 303 }
	controlledprovinces = { 303 }
	nationalprovinces = { 302 300 301 314 303 313 }
	landunit = {
		id = { type = 10043 id = 558 }
		name = "National Army"
		location = 303
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = NAF
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 455 }
	ownedprovinces = { 455 }
	controlledprovinces = { 455 }
	nationalprovinces = { 454 455 458 457 456 }
	landunit = {
		id = { type = 10004 id = 2027 }
		name = "National Army"
		location = 455
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = NAP
	ai = {
		flags = { slavonic = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = italian type = slavonic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 393 }
	ownedprovinces = { 393 }
	controlledprovinces = { 393 }
	nationalprovinces = { 393 399 394 365 392 362 397 }
	navalunit = {
		id = { type = 10078 id = 126 }
		name = "National Fleet"
		location = 393
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10078 id = 378 }
		name = "National Army"
		location = 393
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = NAV
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = cambodian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 428 }
	ownedprovinces = { 428 }
	controlledprovinces = { 428 }
	nationalprovinces = { 430 431 428 427 425 }
	landunit = {
		id = { type = 10081 id = 372 }
		name = "National Army"
		location = 428
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = NIP
	ai = {
		flags = { magyar = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = czech type = magyar }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 315 }
	ownedprovinces = { 315 }
	controlledprovinces = { 315 }
	nationalprovinces = { 328 329 314 299 316 326 327 315 }
	landunit = {
		id = { type = 10063 id = 550 }
		name = "National Army"
		location = 315
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = NOG
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = czech }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 329 }
	ownedprovinces = { 329 }
	controlledprovinces = { 329 }
	nationalprovinces = { 331 312 314 315 328 330 329 }
	landunit = {
		id = { type = 10117 id = 546 }
		name = "National Army"
		location = 329
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = NOR
	ai = {
		flags = { russian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = baltic type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 280 }
	ownedprovinces = { 280 }
	controlledprovinces = { 280 }
	nationalprovinces = { 281 282 277 278 279 285 284 280 }
	landunit = {
		id = { type = 10090 id = 964 }
		name = "National Army"
		location = 280
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = NRM
	ai = {
		flags = { gaelic = yes anglian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = french type = gaelic type = anglosaxon }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 413 }
	ownedprovinces = { 413 }
	controlledprovinces = { 413 }
	nationalprovinces = { 414 412 411 384 413 415 249 248 382 383 }
	navalunit = {
		id = { type = 10141 id = 48 }
		name = "National Fleet"
		location = 413
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10141 id = 422 }
		name = "National Army"
		location = 413
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = NVG
	ai = {
		flags = { ugric = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = russian type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 274 }
	ownedprovinces = { 274 }
	controlledprovinces = { 274 }
	nationalprovinces = { 274 277 275 267 268 270 278 }
	landunit = {
		id = { type = 10112 id = 960 }
		name = "National Army"
		location = 274
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = OHI
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 382 }
	ownedprovinces = { 382 }
	controlledprovinces = { 382 }
	nationalprovinces = { 383 380 382 384 413 248 }
	navalunit = {
		id = { type = 10044 id = 44 }
		name = "National Fleet"
		location = 382
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10044 id = 450 }
		name = "National Army"
		location = 382
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = OLD
	ai = {
		flags = { dutch = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = senegambian type = dutch }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 335 }
	ownedprovinces = { 335 }
	controlledprovinces = { 335 }
	nationalprovinces = { 336 310 334 338 337 335 306 }
	landunit = {
		id = { type = 10101 id = 476 }
		name = "National Army"
		location = 335
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = OMA
	ai = {
		flags = { slavonic = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = greek type = slavonic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 358 }
	ownedprovinces = { 358 }
	controlledprovinces = { 358 }
	nationalprovinces = { 363 356 358 359 361 357 479 478 481 }
	navalunit = {
		id = { type = 10045 id = 166 }
		name = "National Fleet"
		location = 358
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10045 id = 622 }
		name = "National Army"
		location = 358
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ORI
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 456 }
	ownedprovinces = { 456 }
	controlledprovinces = { 456 }
	nationalprovinces = { 455 457 456 }
	landunit = {
		id = { type = 10004 id = 2014 }
		name = "National Army"
		location = 456
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ORL
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 411 }
	ownedprovinces = { 411 }
	controlledprovinces = { 411 }
	nationalprovinces = { 412 413 384 385 386 409 410 411 }
	landunit = {
		id = { type = 10105 id = 424 }
		name = "National Army"
		location = 411
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PAM
	ai = {
		flags = { arabic = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = turkish type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 487 }
	ownedprovinces = { 487 }
	controlledprovinces = { 487 }
	nationalprovinces = { 471 473 486 487 488 490 530 }
	landunit = {
		id = { type = 10004 id = 2036 }
		name = "National Army"
		location = 487
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PAR
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = laotian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 402 }
	ownedprovinces = { 402 }
	controlledprovinces = { 402 }
	nationalprovinces = { 403 389 391 402 401 398 404 397 }
	landunit = {
		id = { type = 10047 id = 390 }
		name = "National Army"
		location = 402
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PEG
	ai = {
		flags = { upper = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = laotian type = abenaki }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 404 }
	ownedprovinces = { 404 }
	controlledprovinces = { 404 }
	nationalprovinces = { 406 405 388 1612 389 404 403 398 401 402 397 }
	navalunit = {
		id = { type = 10202 id = 114 }
		name = "National Fleet"
		location = 404
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10202 id = 512 }
		name = "National Army"
		location = 404
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PER
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = turkish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 482 }
	ownedprovinces = { 482 }
	controlledprovinces = { 482 }
	nationalprovinces = { 477 478 1610 1611 483 476 482 }
	landunit = {
		id = { type = 10048 id = 636 }
		name = "National Army"
		location = 482
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PET
	ai = {
		flags = { egyptian = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = arabic type = nubian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 495 }
	ownedprovinces = { 495 }
	controlledprovinces = { 495 }
	nationalprovinces = { 495 496 490 492 493 494 489 746 747 497 749 750 }
	landunit = {
		id = { type = 10004 id = 513 }
		name = "National Army"
		location = 495
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PEU
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = berber }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 738 }
	ownedprovinces = { 738 }
	controlledprovinces = { 738 }
	nationalprovinces = { 738 737 739 736 821 }
	navalunit = {
		id = { type = 10004 id = 485 }
		name = "National Fleet"
		location = 738
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 486 }
		name = "National Army"
		location = 738
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PFA
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = german }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 345 }
	ownedprovinces = { 345 }
	controlledprovinces = { 345 }
	nationalprovinces = { 377 344 343 333 346 374 375 345 }
	landunit = {
		id = { type = 10049 id = 468 }
		name = "National Army"
		location = 345
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PIC
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 383 }
	ownedprovinces = { 383 }
	controlledprovinces = { 383 }
	nationalprovinces = { 384 385 379 382 383 248 380 }
	landunit = {
		id = { type = 10199 id = 448 }
		name = "National Army"
		location = 383
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PIS
	ai = {
		flags = { umbrian = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = italian type = laotian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 400 }
	ownedprovinces = { 400 }
	controlledprovinces = { 400 }
	nationalprovinces = { 400 401 392 399 397 398 }
	landunit = {
		id = { type = 10124 id = 384 }
		name = "National Army"
		location = 400
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = POD
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = polish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 292 }
	ownedprovinces = { 292 }
	controlledprovinces = { 292 }
	nationalprovinces = { 300 291 288 293 298 299 292 }
	landunit = {
		id = { type = 10177 id = 572 }
		name = "National Army"
		location = 292
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = POI
	ai = {
		flags = { french = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = ashanti type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 418 }
	ownedprovinces = { 418 }
	controlledprovinces = { 418 }
	nationalprovinces = { 424 423 419 410 418 431 425 417 }
	navalunit = {
		id = { type = 10074 id = 58 }
		name = "National Fleet"
		location = 418
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10074 id = 408 }
		name = "National Army"
		location = 418
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = POK
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = baltic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 281 }
	ownedprovinces = { 281 }
	controlledprovinces = { 281 }
	nationalprovinces = { 284 280 282 283 281 }
	landunit = {
		id = { type = 10122 id = 966 }
		name = "National Army"
		location = 281
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = POL
	ai = {
		flags = { czech = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = polish type = czech }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 299 }
	ownedprovinces = { 299 }
	controlledprovinces = { 299 }
	nationalprovinces = { 315 314 300 292 298 316 299 }
	landunit = {
		id = { type = 10013 id = 574 }
		name = "National Army"
		location = 299
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = POM
	ai = {
		flags = { scandinavian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = senegambian type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 302 }
	ownedprovinces = { 302 }
	controlledprovinces = { 302 }
	nationalprovinces = { 301 302 304 303 313 312 }
	navalunit = {
		id = { type = 10096 id = 24 }
		name = "National Fleet"
		location = 302
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10096 id = 556 }
		name = "National Army"
		location = 302
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PRM
	ai = {
		flags = { turkish = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = greek type = turkish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 478 }
	ownedprovinces = { 478 }
	controlledprovinces = { 478 }
	nationalprovinces = { 357 478 477 482 1610 479 358 359 481 }
	navalunit = {
		id = { type = 10116 id = 164 }
		name = "National Fleet"
		location = 478
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10116 id = 630 }
		name = "National Army"
		location = 478
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PRO
	ai = {
		flags = { franco = yes umbrian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = ashanti type = baluchi type = laotian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 406 }
	ownedprovinces = { 406 }
	controlledprovinces = { 406 }
	nationalprovinces = { 422 407 405 406 404 398 397 }
	navalunit = {
		id = { type = 10091 id = 110 }
		name = "National Fleet"
		location = 406
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10091 id = 432 }
		name = "National Army"
		location = 406
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PRT
	ai = {
		flags = { castillian = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = madagasque type = iberian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 434 }
	ownedprovinces = { 434 }
	controlledprovinces = { 434 }
	nationalprovinces = { 434 441 440 435 432 433 }
	navalunit = {
		id = { type = 10139 id = 96 }
		name = "National Fleet"
		location = 434
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10139 id = 342 }
		name = "National Army"
		location = 434
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PRU
	ai = {
		flags = { polish = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = baltic type = polish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 290 }
	ownedprovinces = { 290 }
	controlledprovinces = { 290 }
	nationalprovinces = { 282 283 289 290 288 291 300 301 }
	navalunit = {
		id = { type = 10004 id = 20 }
		name = "National Fleet"
		location = 290
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 564 }
		name = "National Army"
		location = 290
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PSK
	ai = {
		flags = { ugric = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = russian type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 277 }
	ownedprovinces = { 277 }
	controlledprovinces = { 277 }
	nationalprovinces = { 276 275 274 278 280 282 277 }
	landunit = {
		id = { type = 10086 id = 958 }
		name = "National Army"
		location = 277
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PUR
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = anglosaxon }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 244 }
	ownedprovinces = { 244 }
	controlledprovinces = { 244 }
	nationalprovinces = { 242 243 246 245 241 244 }
	landunit = {
		id = { type = 10185 id = 304 }
		name = "National Army"
		location = 244
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = QAR
	ai = {
		flags = { czech = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = abenaki type = czech }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 348 }
	ownedprovinces = { 348 }
	controlledprovinces = { 348 }
	nationalprovinces = { 349 372 347 330 327 350 348 }
	landunit = {
		id = { type = 10138 id = 526 }
		name = "National Army"
		location = 348
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = QUE
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = romanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 320 }
	ownedprovinces = { 320 }
	controlledprovinces = { 320 }
	nationalprovinces = { 318 322 321 320 319 }
	landunit = {
		id = { type = 10149 id = 598 }
		name = "National Army"
		location = 320
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = RAG
	ai = {
		flags = { greek = yes italian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = slavonic type = greek type = italian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 362 }
	ownedprovinces = { 362 }
	controlledprovinces = { 362 }
	nationalprovinces = { 365 364 363 362 361 359 394 393 820 }
	navalunit = {
		id = { type = 10127 id = 144 }
		name = "National Fleet"
		location = 362
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10127 id = 614 }
		name = "National Army"
		location = 362
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ROM
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = laotian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 391 }
	ownedprovinces = { 391 }
	controlledprovinces = { 391 }
	nationalprovinces = { 392 401 402 389 390 391 368 370 }
	landunit = {
		id = { type = 10136 id = 388 }
		name = "National Army"
		location = 391
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ROY
	ai = {
		flags = { turkish = yes }
	}
	policy = {
		aristocracy = 1
		land = 1
	}
	culture = { type = greek type = turkish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 481 }
	ownedprovinces = { 481 }
	controlledprovinces = { 481 }
	nationalprovinces = { 360 359 358 478 1610 1611 479 481 }
	navalunit = {
		id = { type = 10203 id = 156 }
		name = "National Fleet"
		location = 481
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10203 id = 334 }
		name = "National Army"
		location = 481
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = RYA
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 448 }
	ownedprovinces = { 448 }
	controlledprovinces = { 448 }
	nationalprovinces = { 270 448 272 447 452 449 279 }
	landunit = {
		id = { type = 10113 id = 984 }
		name = "National Army"
		location = 448
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SAC
	ai = {
		flags = { czech = yes lower = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = german type = czech type = senegambian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 331 }
	ownedprovinces = { 331 }
	controlledprovinces = { 331 }
	nationalprovinces = { 347 332 311 312 329 330 331 }
	landunit = {
		id = { type = 10050 id = 496 }
		name = "National Army"
		location = 331
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SAR
	ai = {
		flags = { umbrian = yes egyptian = yes }
	}
	policy = {
		aristocracy = 0
		land = 0
	}
	culture = { type = italian type = laotian type = nubian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 397 }
	ownedprovinces = { 397 }
	controlledprovinces = { 397 }
	nationalprovinces = { 397 406 404 403 402 401 400 399 393 396 395 398 739 740 }
	navalunit = {
		id = { type = 10085 id = 124 }
		name = "National Fleet"
		location = 397
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10085 id = 322 }
		name = "National Army"
		location = 397
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SAV
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = baluchi }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 405 }
	ownedprovinces = { 405 }
	controlledprovinces = { 405 }
	nationalprovinces = { 406 404 388 387 408 407 405 }
	landunit = {
		id = { type = 10051 id = 434 }
		name = "National Army"
		location = 405
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SCO
	ai = {
		flags = { anglian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = gaelic type = anglosaxon }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 239 }
	ownedprovinces = { 239 }
	controlledprovinces = { 239 }
	nationalprovinces = { 237 238 239 240 232 233 243 242 }
	navalunit = {
		id = { type = 10052 id = 72 }
		name = "National Fleet"
		location = 239
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10052 id = 292 }
		name = "National Army"
		location = 239
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SEI
	ai = {
		flags = { slavonic = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = abenaki type = slavonic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 369 }
	ownedprovinces = { 369 }
	controlledprovinces = { 369 }
	nationalprovinces = { 370 371 350 351 352 367 368 369 }
	landunit = {
		id = { type = 10175 id = 530 }
		name = "National Army"
		location = 369
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SEL
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 531 }
	ownedprovinces = { 531 }
	controlledprovinces = { 531 }
	nationalprovinces = { 488 489 530 531 }
	landunit = {
		id = { type = 10004 id = 521 }
		name = "National Army"
		location = 531
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SER
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = slavonic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 355 }
	ownedprovinces = { 355 }
	controlledprovinces = { 355 }
	nationalprovinces = { 364 366 354 322 356 363 355 }
	landunit = {
		id = { type = 10129 id = 610 }
		name = "National Army"
		location = 355
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SEV
	ai = {
		flags = { tatar = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = armenian type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 469 }
	ownedprovinces = { 469 }
	controlledprovinces = { 469 }
	nationalprovinces = { 465 466 468 470 469 475 }
	navalunit = {
		id = { type = 10059 id = 182 }
		name = "National Fleet"
		location = 469
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10059 id = 660 }
		name = "National Army"
		location = 469
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SHA
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = magyar }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 324 }
	ownedprovinces = { 324 }
	controlledprovinces = { 324 }
	nationalprovinces = { 353 325 324 317 323 354 }
	landunit = {
		id = { type = 10147 id = 588 }
		name = "National Army"
		location = 324
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SHL
	ai = {
		flags = { scandinavian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = senegambian type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 306 }
	ownedprovinces = { 306 }
	controlledprovinces = { 306 }
	nationalprovinces = { 251 305 336 309 306 335 307 304 }
	navalunit = {
		id = { type = 10084 id = 30 }
		name = "National Fleet"
		location = 306
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10084 id = 480 }
		name = "National Army"
		location = 306
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SIB
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = magyar }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 317 }
	ownedprovinces = { 317 }
	controlledprovinces = { 317 }
	nationalprovinces = { 325 316 298 318 317 324 323 }
	landunit = {
		id = { type = 10053 id = 586 }
		name = "National Army"
		location = 317
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SIC
	policy = {
		aristocracy = 2
		land = 2
	}
	culture = { type = italian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 396 }
	ownedprovinces = { 396 }
	controlledprovinces = { 396 }
	nationalprovinces = { 396 819 395 397 }
	navalunit = {
		id = { type = 10071 id = 128 }
		name = "National Fleet"
		location = 396
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10071 id = 326 }
		name = "National Army"
		location = 396
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SIE
	ai = {
		flags = { romanian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = magyar type = romanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 323 }
	ownedprovinces = { 323 }
	controlledprovinces = { 323 }
	nationalprovinces = { 354 324 317 318 322 323 }
	landunit = {
		id = { type = 10125 id = 594 }
		name = "National Army"
		location = 323
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SIL
	ai = {
		flags = { polish = yes lower = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = czech  type = polish type = senegambian}
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 314 }
	ownedprovinces = { 314 }
	controlledprovinces = { 314 }
	nationalprovinces = { 329 312 313 303 300 299 315 314 }
	landunit = {
		id = { type = 10205 id = 552 }
		name = "National Army"
		location = 314
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SKA
	ai = {
		flags = { lower = yes }
	}
	policy = {
		aristocracy = 5
		land = 5
	}
	culture = { type = scandinavian type = senegambian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 251 }
	ownedprovinces = { 251 }
	controlledprovinces = { 251 }
	nationalprovinces = { 251 307 309 253 252 306 305 304 308 }
	navalunit = {
		id = { type = 10004 id = 1018 }
		name = "National Fleet"
		location = 251
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2018 }
		name = "National Army"
		location = 251
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SLO
	ai = {
		flags = { polish = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = magyar type = polish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 316 }
	ownedprovinces = { 316 }
	controlledprovinces = { 316 }
	nationalprovinces = { 315 299 298 317 325 326 316 }
	landunit = {
		id = { type = 10160 id = 578 }
		name = "National Army"
		location = 316
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SLZ
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = abenaki }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 350 }
	ownedprovinces = { 350 }
	controlledprovinces = { 350 }
	nationalprovinces = { 349 348 327 351 369 371 350 }
	landunit = {
		id = { type = 10209 id = 538 }
		name = "National Army"
		location = 350
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SMO
	ai = {
		flags = { russian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ruthenian type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 285 }
	ownedprovinces = { 285 }
	controlledprovinces = { 285 }
	nationalprovinces = { 287 284 280 286 285 279 }
	landunit = {
		id = { type = 10215 id = 972 }
		name = "National Army"
		location = 285
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SON
	ai = {
		flags = { ruthenian = yes tatar = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = romanian type = ruthenian type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 296 }
	ownedprovinces = { 296 }
	controlledprovinces = { 296 }
	nationalprovinces = { 296 319 318 297 295 462 463 464 }
	navalunit = {
		id = { type = 10058 id = 172 }
		name = "National Fleet"
		location = 296
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10058 id = 582 }
		name = "National Army"
		location = 296
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SPR
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 385 }
	ownedprovinces = { 385 }
	controlledprovinces = { 385 }
	nationalprovinces = { 383 379 376 386 411 384 385 }
	landunit = {
		id = { type = 10004 id = 444 }
		name = "National Army"
		location = 385
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = STR
	ai = {
		flags = { middle = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = abenaki type = german }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 374 }
	ownedprovinces = { 374 }
	controlledprovinces = { 374 }
	nationalprovinces = { 345 375 374 387 388 373 346 }
	landunit = {
		id = { type = 10205 id = 553 }
		name = "National Army"
		location = 374
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = STT
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = senegambian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 304 }
	ownedprovinces = { 304 }
	controlledprovinces = { 304 }
	nationalprovinces = { 251 304 309 307 306 305 311 312 302 }
	navalunit = {
		id = { type = 10028 id = 26 }
		name = "National Fleet"
		location = 304
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10028 id = 490 }
		name = "National Army"
		location = 304
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SUD
	ai = {
		flags = { arabic = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = nubian type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 750 }
	ownedprovinces = { 750 }
	controlledprovinces = { 750 }
	nationalprovinces = { 750 748 749 747 746 494 495 496 497 }
	landunit = {
		id = { type = 10004 id = 531 }
		name = "National Army"
		location = 750
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SUZ
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 271 }
	ownedprovinces = { 271 }
	controlledprovinces = { 271 }
	nationalprovinces = { 271 268 269 270 272 446 }
	landunit = {
		id = { type = 10004 id = 2015 }
		name = "National Army"
		location = 271
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SWA
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = italian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 399 }
	ownedprovinces = { 399 }
	controlledprovinces = { 399 }
	nationalprovinces = { 400 392 399 393 397 398 }
	landunit = {
		id = { type = 10024 id = 380 }
		name = "National Army"
		location = 399
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SWE
	ai = {
		flags = { ugric = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = scandinavian type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 254 }
	ownedprovinces = { 254 }
	controlledprovinces = { 254 }
	nationalprovinces = { 308 254 252 253 257 1469 342 265 }
	navalunit = {
		id = { type = 10004 id = 1003 }
		name = "National Fleet"
		location = 254
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2003 }
		name = "National Army"
		location = 254
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = SYR
	ai = {
		flags = { turkish = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = arabic type = turkish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 490 }
	ownedprovinces = { 490 }
	controlledprovinces = { 490 }
	nationalprovinces = { 490 491 492 495 488 489 487 485 486 }
	landunit = {
		id = { type = 10004 id = 516 }
		name = "National Army"
		location = 490
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TAN
	policy = {
		aristocracy = 4
		land = 4
	}
	culture = { type = berber }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 732 }
	ownedprovinces = { 732 }
	controlledprovinces = { 732 }
	nationalprovinces = { 732 733 445 }
	navalunit = {
		id = { type = 10004 id = 475 }
		name = "National Fleet"
		location = 732
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 476 }
		name = "National Army"
		location = 732
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TAU
	ai = {
		flags = { czech = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = magyar type = czech }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 326 }
	ownedprovinces = { 326 }
	controlledprovinces = { 326 }
	nationalprovinces = { 351 352 325 353 316 315 327 326 }
	landunit = {
		id = { type = 10180 id = 542 }
		name = "National Army"
		location = 326
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TEK
	ai = {
		flags = { greek = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = turkish type = greek }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 1610 }
	ownedprovinces = { 1610 }
	controlledprovinces = { 1610 }
	nationalprovinces = { 1610 482 1611 481 478 484 }
	navalunit = {
		id = { type = 10192 id = 158 }
		name = "National Fleet"
		location = 1610
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10192 id = 632 }
		name = "National Army"
		location = 1610
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = THE
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = nubian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 742 }
	ownedprovinces = { 742 }
	controlledprovinces = { 742 }
	nationalprovinces = { 480 742 741 743 744 }
	landunit = {
		id = { type = 10004 id = 494 }
		name = "National Army"
		location = 742
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = THU
	ai = {
		flags = { upper = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = german type = abenaki }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 347 }
	ownedprovinces = { 347 }
	controlledprovinces = { 347 }
	nationalprovinces = { 346 333 331 330 348 372 373 347 332 }
	landunit = {
		id = { type = 10056 id = 500 }
		name = "National Army"
		location = 347
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TIB
	ai = {
		flags = { magyar = yes romanian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = polish type = magyar type = romanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 298 }
	ownedprovinces = { 298 }
	controlledprovinces = { 298 }
	nationalprovinces = { 299 316 317 318 297 293 292 298 }
	landunit = {
		id = { type = 10169 id = 576 }
		name = "National Army"
		location = 298
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TIM
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = nubian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 743 }
	ownedprovinces = { 743 }
	controlledprovinces = { 743 }
	nationalprovinces = { 743 742 744 746 747 }
	landunit = {
		id = { type = 10004 id = 495 }
		name = "National Army"
		location = 743
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TOS
	ai = {
		flags = { italian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = laotian type = italian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 401 }
	ownedprovinces = { 401 }
	controlledprovinces = { 401 }
	nationalprovinces = { 402 391 392 401 400 398 404 403 397 }
	navalunit = {
		id = { type = 10057 id = 120 }
		name = "National Fleet"
		location = 401
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10057 id = 386 }
		name = "National Army"
		location = 401
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TOU
	ai = {
		flags = { franco = yes catalan = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = ashanti type = baluchi type = cambodian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 422 }
	ownedprovinces = { 422 }
	controlledprovinces = { 422 }
	nationalprovinces = { 426 423 421 408 407 406 422 427 821 }
	landunit = {
		id = { type = 10143 id = 398 }
		name = "National Army"
		location = 422
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TOX
	ai = {
		flags = { arabic = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = nubian type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 747 }
	ownedprovinces = { 747 }
	controlledprovinces = { 747 }
	nationalprovinces = { 743 746 747 494 495 496 497 749 750 }
	navalunit = {
		id = { type = 10004 id = 502 }
		name = "National Fleet"
		location = 747
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 503 }
		name = "National Army"
		location = 747
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TRE
	ai = {
		flags = { armenian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = turkish type = armenian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 475 }
	ownedprovinces = { 475 }
	controlledprovinces = { 475 }
	nationalprovinces = { 470 469 1609 475 476 474 473 472 }
	navalunit = {
		id = { type = 10135 id = 184 }
		name = "National Fleet"
		location = 475
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10135 id = 646 }
		name = "National Army"
		location = 475
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TRI
	ai = {
		flags = { italian = yes }
	}
	policy = {
		aristocracy = 5
		land = 5
	}
	culture = { type = nubian type = italian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 740 }
	ownedprovinces = { 740 }
	controlledprovinces = { 740 }
	nationalprovinces = { 739 740 741 819 395 396 397 }
	navalunit = {
		id = { type = 10004 id = 489 }
		name = "National Fleet"
		location = 740
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 490 }
		name = "National Army"
		location = 740
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TUN
	ai = {
		flags = { italian = yes }
	}
	policy = {
		aristocracy = 5
		land = 5
	}
	culture = { type = nubian type = italian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 739 }
	ownedprovinces = { 739 }
	controlledprovinces = { 739 }
	nationalprovinces = { 739 738 740 397 819 }
	navalunit = {
		id = { type = 10004 id = 487 }
		name = "National Fleet"
		location = 739
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 488 }
		name = "National Army"
		location = 739
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TVE
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = russian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 278 }
	ownedprovinces = { 278 }
	controlledprovinces = { 278 }
	nationalprovinces = { 280 277 274 270 279 278 }
	landunit = {
		id = { type = 10115 id = 962 }
		name = "National Army"
		location = 278
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = TYR
	ai = {
		flags = { umbrian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = abenaki type = laotian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 371 }
	ownedprovinces = { 371 }
	controlledprovinces = { 371 }
	nationalprovinces = { 1612 372 349 350 369 370 390 389 371 }
	landunit = {
		id = { type = 10204 id = 522 }
		name = "National Army"
		location = 371
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U01
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = madagasque }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 441 }
	ownedprovinces = { 441 }
	controlledprovinces = { 441 }
	nationalprovinces = { 434 440 442 441 }
	navalunit = {
		id = { type = 10004 id = 98 }
		name = "National Fleet"
		location = 441
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 340 }
		name = "National Army"
		location = 441
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U02
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = magyar }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 325 }
	ownedprovinces = { 325 }
	controlledprovinces = { 325 }
	nationalprovinces = { 325 324 353 326 316 317 }
	landunit = {
		id = { type = 10032 id = 584 }
		name = "National Army"
		location = 325
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U03
	ai = {
		flags = { greek = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = turkish type = greek }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 477 }
	ownedprovinces = { 477 }
	controlledprovinces = { 477 }
	nationalprovinces = { 478 357 477 482 476 1609 }
	landunit = {
		id = { type = 10010 id = 634 }
		name = "National Army"
		location = 477
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U06
	ai = {
		flags = { baltic = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = russian type = baltic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 279 }
	ownedprovinces = { 279 }
	controlledprovinces = { 279 }
	nationalprovinces = { 280 279 286 278 270 448 449 285 }
	landunit = {
		id = { type = 10007 id = 976 }
		name = "National Army"
		location = 279
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U07
	ai = {
		flags = { slavonic = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = magyar type = slavonic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 354 }
	ownedprovinces = { 354 }
	controlledprovinces = { 354 }
	nationalprovinces = { 366 353 324 323 322 355 354 }
	landunit = {
		id = { type = 10040 id = 592 }
		name = "National Army"
		location = 354
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U08
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = ugric }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 276 }
	ownedprovinces = { 276 }
	controlledprovinces = { 276 }
	nationalprovinces = { 265 275 277 282 276 }
	navalunit = {
		id = { type = 10079 id = 12 }
		name = "National Fleet"
		location = 276
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10079 id = 956 }
		name = "National Army"
		location = 276
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U10
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 257 }
	ownedprovinces = { 257 }
	controlledprovinces = { 257 }
	nationalprovinces = { 255 253 254 257 1469 381 }
	landunit = {
		id = { type = 10004 id = 2011 }
		name = "National Army"
		location = 257
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U11
	ai = {
		flags = { catalan = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = iberian type = cambodian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 436 }
	ownedprovinces = { 436 }
	controlledprovinces = { 436 }
	nationalprovinces = { 440 435 436 430 437 439 }
	landunit = {
		id = { type = 10111 id = 364 }
		name = "National Army"
		location = 436
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U12
	ai = {
		flags = { umbrian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = italian type = laotian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 392 }
	ownedprovinces = { 392 }
	controlledprovinces = { 392 }
	nationalprovinces = { 392 393 399 400 401 391 368 370 390 }
	navalunit = {
		id = { type = 10080 id = 136 }
		name = "National Fleet"
		location = 392
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10080 id = 382 }
		name = "National Army"
		location = 392
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U15
	ai = {
		flags = { castillian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = cambodian type = iberian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 437 }
	ownedprovinces = { 437 }
	controlledprovinces = { 437 }
	nationalprovinces = { 438 439 436 430 429 437 821 }
	navalunit = {
		id = { type = 10170 id = 106 }
		name = "National Fleet"
		location = 437
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10170 id = 366 }
		name = "National Army"
		location = 437
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U25
	ai = {
		flags = { scandinavian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = ugric type = scandinavian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 342 }
	ownedprovinces = { 342 }
	controlledprovinces = { 342 }
	nationalprovinces = { 263 342 264 265 341 1469 254 }
	navalunit = {
		id = { type = 10004 id = 1005 }
		name = "National Fleet"
		location = 342
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 2005 }
		name = "National Army"
		location = 342
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U26
	ai = {
		flags = { romanian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = slavonic type = romanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 321 }
	ownedprovinces = { 321 }
	controlledprovinces = { 321 }
	nationalprovinces = { 321 357 356 322 320 }
	navalunit = {
		id = { type = 10055 id = 170 }
		name = "National Fleet"
		location = 321
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10055 id = 626 }
		name = "National Army"
		location = 321
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U29
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = slavonic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 365 }
	ownedprovinces = { 365 }
	controlledprovinces = { 365 }
	nationalprovinces = { 362 364 365 368 393 366 }
	navalunit = {
		id = { type = 10039 id = 142 }
		name = "National Fleet"
		location = 365
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10039 id = 606 }
		name = "National Army"
		location = 365
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U30
	policy = {
		aristocracy = 4
		land = 4
	}
	culture = { type = greek }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 479 }
	ownedprovinces = { 479 }
	controlledprovinces = { 479 }
	nationalprovinces = { 359 358 479 478 481 }
	navalunit = {
		id = { type = 10017 id = 162 }
		name = "National Fleet"
		location = 479
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10017 id = 336 }
		name = "National Army"
		location = 479
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U31
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = nubian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 748 }
	ownedprovinces = { 748 }
	controlledprovinces = { 748 }
	nationalprovinces = { 748 747 749 750 }
	landunit = {
		id = { type = 10004 id = 532 }
		name = "National Army"
		location = 748
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U32
	ai = {
		flags = { arabic = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = nubian type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 749 }
	ownedprovinces = { 749 }
	controlledprovinces = { 749 }
	nationalprovinces = { 749 748 750 747 746 494 495 496 497 }
	navalunit = {
		id = { type = 10004 id = 536 }
		name = "National Fleet"
		location = 749
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 533 }
		name = "National Army"
		location = 749
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U33
	ai = {
		flags = { egyptian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = arabic type = nubian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 497 }
	ownedprovinces = { 497 }
	controlledprovinces = { 497 }
	nationalprovinces = { 497 750 749 747 494 495 496 746 }
	navalunit = {
		id = { type = 10004 id = 537 }
		name = "National Fleet"
		location = 497
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 534 }
		name = "National Army"
		location = 497
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U34
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 491 }
	ownedprovinces = { 491 }
	controlledprovinces = { 491 }
	nationalprovinces = { 490 491 492 484 485 483 }
	navalunit = {
		id = { type = 10004 id = 510 }
		name = "National Fleet"
		location = 491
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 511 }
		name = "National Army"
		location = 491
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U35
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 492 }
	ownedprovinces = { 492 }
	controlledprovinces = { 492 }
	nationalprovinces = { 483 484 485 492 491 493 495 490 494 }
	navalunit = {
		id = { type = 10004 id = 508 }
		name = "National Fleet"
		location = 492
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 509 }
		name = "National Army"
		location = 492
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U36
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 488 }
	ownedprovinces = { 488 }
	controlledprovinces = { 488 }
	nationalprovinces = { 488 489 490 530 531 487 }
	landunit = {
		id = { type = 10004 id = 517 }
		name = "National Army"
		location = 488
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U37
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 530 }
	ownedprovinces = { 530 }
	controlledprovinces = { 530 }
	nationalprovinces = { 530 531 487 488 }
	landunit = {
		id = { type = 10004 id = 520 }
		name = "National Army"
		location = 530
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U38
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = french }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 384 }
	ownedprovinces = { 384 }
	controlledprovinces = { 384 }
	nationalprovinces = { 383 385 411 413 384 248 382 }
	navalunit = {
		id = { type = 10034 id = 46 }
		name = "National Fleet"
		location = 384
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10034 id = 446 }
		name = "National Army"
		location = 384
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = U39
	ai = {
		flags = { tatar = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = romanian type = albanian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 319 }
	ownedprovinces = { 319 }
	controlledprovinces = { 319 }
	nationalprovinces = { 320 318 319 296 463 464 }
	landunit = {
		id = { type = 10016 id = 602 }
		name = "National Army"
		location = 319
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = UKR
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = ruthenian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 295 }
	ownedprovinces = { 295 }
	controlledprovinces = { 295 }
	nationalprovinces = { 297 294 295 450 461 462 296 }
	landunit = {
		id = { type = 10068 id = 202 }
		name = "National Army"
		location = 295
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ULS
	ai = {
		flags = { anglian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = gaelic type = anglosaxon }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 232 }
	ownedprovinces = { 232 }
	controlledprovinces = { 232 }
	nationalprovinces = { 231 233 232 239 237 240 242 243 }
	navalunit = {
		id = { type = 10207 id = 62 }
		name = "National Fleet"
		location = 232
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10207 id = 188 }
		name = "National Army"
		location = 232
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = USA
	ai = {
		flags = { baltic = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = polish type = baltic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 291 }
	ownedprovinces = { 291 }
	controlledprovinces = { 291 }
	nationalprovinces = { 300 290 291 288 292 }
	landunit = {
		id = { type = 10067 id = 568 }
		name = "National Army"
		location = 291
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = UZB
	ai = {
		flags = { ruthenian = yes polish = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = romanian type = ruthenian type = polish }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 297 }
	ownedprovinces = { 297 }
	controlledprovinces = { 297 }
	nationalprovinces = { 297 298 294 295 296 318 293 }
	landunit = {
		id = { type = 10119 id = 580 }
		name = "National Army"
		location = 297
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = WAL
	ai = {
		flags = { slavonic = yes magyar = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = romanian type = slavonic type = magyar }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 322 }
	ownedprovinces = { 322 }
	controlledprovinces = { 322 }
	nationalprovinces = { 355 354 323 318 320 321 356 322 }
	landunit = {
		id = { type = 10060 id = 596 }
		name = "National Army"
		location = 322
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = VEN
	ai = {
		flags = { upper = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = laotian type = abenaki }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 370 }
	ownedprovinces = { 370 }
	controlledprovinces = { 370 }
	nationalprovinces = { 392 391 390 370 368 369 371 }
	navalunit = {
		id = { type = 10011 id = 138 }
		name = "National Fleet"
		location = 370
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10011 id = 520 }
		name = "National Army"
		location = 370
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = VER
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = nubian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 744 }
	ownedprovinces = { 744 }
	controlledprovinces = { 744 }
	nationalprovinces = { 480 744 742 743 745 746 }
	navalunit = {
		id = { type = 10004 id = 496 }
		name = "National Fleet"
		location = 744
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 497 }
		name = "National Army"
		location = 744
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = VIE
	policy = {
		aristocracy = 4
		land = 4
	}
	culture = { type = nubian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 745 }
	ownedprovinces = { 745 }
	controlledprovinces = { 745 }
	nationalprovinces = { 480 744 745 746 }
	navalunit = {
		id = { type = 10004 id = 498 }
		name = "National Fleet"
		location = 745
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10004 id = 499 }
		name = "National Army"
		location = 745
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = VIJ
	ai = {
		flags = { arabic = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = nubian type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 746 }
	ownedprovinces = { 746 }
	controlledprovinces = { 746 }
	nationalprovinces = { 480 743 744 745 746 747 494 495 496 497 749 750 }
	landunit = {
		id = { type = 10004 id = 501 }
		name = "National Army"
		location = 746
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = WLS
	ai = {
		flags = { anglian = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = gaelic type = anglosaxon }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 243 }
	ownedprovinces = { 243 }
	controlledprovinces = { 243 }
	nationalprovinces = { 242 244 246 243 239 237 240 232 233 234 250 }
	navalunit = {
		id = { type = 10104 id = 90 }
		name = "National Fleet"
		location = 243
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10104 id = 302 }
		name = "National Army"
		location = 243
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = VOL
	ai = {
		flags = { ruthenian = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = polish type = ruthenian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 293 }
	ownedprovinces = { 293 }
	controlledprovinces = { 293 }
	nationalprovinces = { 293 288 287 294 297 298 292 }
	landunit = {
		id = { type = 10171 id = 570 }
		name = "National Army"
		location = 293
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = WUR
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = abenaki }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 372 }
	ownedprovinces = { 372 }
	controlledprovinces = { 372 }
	nationalprovinces = { 373 347 348 349 372 1612 371 }
	landunit = {
		id = { type = 10061 id = 506 }
		name = "National Army"
		location = 372
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = XHO
	ai = {
		flags = { egyptian = yes }
	}
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = arabic type = nubian }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 494 }
	ownedprovinces = { 494 }
	controlledprovinces = { 494 }
	nationalprovinces = { 484 494 493 495 746 496 747 492 497 749 750 }
	landunit = {
		id = { type = 10004 id = 505 }
		name = "National Army"
		location = 494
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = YOR
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = anglosaxon }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 241 }
	ownedprovinces = { 241 }
	controlledprovinces = { 241 }
	nationalprovinces = { 240 242 244 241 245 }
	navalunit = {
		id = { type = 10073 id = 78 }
		name = "National Fleet"
		location = 241
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10073 id = 300 }
		name = "National Army"
		location = 241
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ZAN
	ai = {
		flags = { berber = yes }
	}
	policy = {
		aristocracy = 8
		land = 8
	}
	culture = { type = iberian type = berber }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 439 }
	ownedprovinces = { 439 }
	controlledprovinces = { 439 }
	nationalprovinces = { 443 440 436 437 438 444 439 }
	landunit = {
		id = { type = 10008 id = 360 }
		name = "National Army"
		location = 439
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ZAP
	policy = {
		aristocracy = 5
		land = 5
	}
	culture = { type = baltic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 289 }
	ownedprovinces = { 289 }
	controlledprovinces = { 289 }
	nationalprovinces = { 283 290 289 282 }
	navalunit = {
		id = { type = 10152 id = 18 }
		name = "National Fleet"
		location = 289
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10152 id = 950 }
		name = "National Army"
		location = 289
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ZEE
	ai = {
		flags = { middle = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = dutch type = german }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 340 }
	ownedprovinces = { 340 }
	controlledprovinces = { 340 }
	nationalprovinces = { 380 378 344 343 334 338 339 340 337 }
	navalunit = {
		id = { type = 10009 id = 40 }
		name = "National Fleet"
		location = 340
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10009 id = 458 }
		name = "National Army"
		location = 340
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ZIM
	ai = {
		flags = { gaelic = yes }
	}
	policy = {
		aristocracy = 6
		land = 6
	}
	culture = { type = anglosaxon type = gaelic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 249 }
	ownedprovinces = { 249 }
	controlledprovinces = { 249 }
	nationalprovinces = { 249 250 246 247 248 413 414 415 }
	navalunit = {
		id = { type = 10162 id = 84 }
		name = "National Fleet"
		location = 249
		morale = 2
		warships = 5
		galleys = 5
		transports = 5
	}
	landunit = {
		id = { type = 10162 id = 312 }
		name = "National Army"
		location = 249
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = ZUL
	policy = {
		aristocracy = 7
		land = 7
	}
	culture = { type = arabic }
	colonialattempts = 10
	colonialnation = yes
	major = no
	treasury = 400
	manpower = 0
	landpercentage = 1
	knownprovinces = { 493 }
	ownedprovinces = { 493 }
	controlledprovinces = { 493 }
	nationalprovinces = { 484 493 492 494 495 }
	landunit = {
		id = { type = 10004 id = 507 }
		name = "National Army"
		location = 493
		morale = 2
		inf = 5000
		cav = 5000
	}
}

country = {
	tag = PAP
	ai = {
		flags = { NoRandomEvents = yes }
	}
	ai = tahiti.ai
	culture = { type = han }
	treasury = 10000
	landpercentage = 1
	religion = { type = confucianism }
	knownprovinces = { 814 }
	ownedprovinces = { 814 }
	controlledprovinces = { 814 }
	nationalprovinces = { 814 }
	landunit = {
		id = { type = 10046 id = 2 }
		name = "The Guardians"
		location = 814
		morale = 6
		inf = 1000
	}
	loansize = 10000
}

country = {
	tag = MER
	landpercentage = 1
	religion = { type = confucianism }
}

country = {
	tag = REB
	landpercentage = 1
	religion = { type = buddhism }
        knownprovinces = {   231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253
 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283
 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313
 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343
 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373
 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403
 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433
 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459 460 461 462 463
 464 465 466 467 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493
 494 495 496 497 530 531 732 733 734 735 736 737 738 739 740 741 742 743 744 745 746 747 748 749 750 806 819 820 821 839
 840 841 842 843 869 870 871 872 873 874 875 876 877 878 879 880 881 882 917 918 919 920 921 922 923 924 925 926 927 928
 929 930 931 932 933 934 935 936 937 938 939 978 979 980 981 982 983 984 985 986 987 988 989 990 991 992 993 994 995 996
 997 998 999 1000 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1057 1058 1059
 1060 1326 1327 1331 1361 1362 1411 1419 1429 1430 1435 1461 1469 1470 1609 1610 1611 1612 1613 }
}
cot = { location = 814 } #Tahiti
