country = {
	tag = ADE
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Elvas"
		population = 20000
		location = 442
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = AFG
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Pest"
		population = 20000
		location = 353
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = AKK
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 0
		#sunni = 10
		#shiite = 0
	}
	city = {
		name = "Bitlis"
		population = 20000
		location = 473
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ALB
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Durrës"
		population = 20000
		location = 361
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ALD
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Al-Djazair"
		population = 20000
		location = 737
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ALE
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Aleppo"
		population = 20000
		location = 485
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ALI
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = shiite
		#catholic = -10
		#orthodox = 0
		#sunni = 0
		#shiite = 10
	}
	city = {
		name = "Derbent"
		population = 20000
		location = 471
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ALM
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Saratov"
		population = 20000
		location = 452
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ALT
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Kerch"
		population = 20000
		location = 465
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = AMG
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Kalmar"
		population = 20000
		location = 252
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = AMI
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Mogilev"
		population = 20000
		location = 287
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ANH
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Dessau"
		population = 20000
		location = 332
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ANJ
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Le Mans"
		population = 20000
		location = 412
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ANN
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Badajoz"
		population = 20000
		location = 440
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = APA
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Älvsborg"
		population = 20000
		location = 253
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = APU
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Taranto"
		population = 20000
		location = 394
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = AQU
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Toulouse"
		population = 20000
		location = 423
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ARA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Tabuk"
		population = 20000
		location = 496
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ARG
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Saragosa"
		population = 20000
		location = 430
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ARK
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Yekaterinoslav"
		population = 20000
		location = 462
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ARM
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Erevan"
		population = 20000
		location = 472
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ART
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Arras"
		population = 20000
		location = 379
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ASH
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Laibach"
		population = 20000
		location = 367
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ASS
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Bern"
		population = 20000
		location = 388
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = AST
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Astrakhan"
		population = 20000
		location = 457
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ASU
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -5
		#orthodox = 10
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Vologda"
		population = 20000
		location = 268
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ATH
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -5
		#orthodox = 10
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Nafplion"
		population = 20000
		location = 360
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ATJ
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 10
		#orthodox = -10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Gibraltar"
		population = 20000
		location = 445
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = AUV
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Clermont"
		population = 20000
		location = 420
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = AYU
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Bilbao"
		population = 20000
		location = 431
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = AYY
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Poltava"
		population = 20000
		location = 461
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = AZT
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Burgos"
		population = 20000
		location = 432
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BAD
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Rastatt"
		population = 20000
		location = 373
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BAE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Samara"
		population = 20000
		location = 454
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BAL
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Azov"
		population = 20000
		location = 466
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BAN
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "La Corunna"
		population = 20000
		location = 433
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BAS
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Pyatigorsk"
		population = 20000
		location = 468
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BAY
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "München"
		population = 20000
		location = 349
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BEA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Pau"
		population = 20000
		location = 425
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BEI
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Aurillac"
		population = 20000
		location = 421
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BEN
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 10
		#orthodox = -10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Cartagena"
		population = 20000
		location = 438
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BGL
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Voronezh"
		population = 20000
		location = 449
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BOH
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Prag"
		population = 20000
		location = 328
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BOS
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Sarajevo"
		population = 20000
		location = 364
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BOU
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Tours"
		population = 20000
		location = 410
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BRA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Berlin"
		population = 20000
		location = 312
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BRE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Bremen"
		population = 20000
		location = 336
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BRI
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Brest"
		population = 20000
		location = 415
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BRZ
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Gerona"
		population = 20000
		location = 427
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BUK
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Ulge"
		population = 20000
		location = 467
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BUL
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Sofia"
		population = 20000
		location = 356
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BUR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Dijon"
		population = 20000
		location = 409
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = BYZ
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Constantinople"
		population = 20000
		location = 357
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CAL
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Ankara"
		population = 20000
		location = 476
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CAM
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Perpignan"
		population = 20000
		location = 426
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CAN
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Kastamonu"
		population = 20000
		location = 1609
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CAT
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Barcelona"
		population = 20000
		location = 429
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CHA
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Bordeaux"
		population = 20000
		location = 424
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CHE
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Kharkov"
		population = 20000
		location = 460
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CHG
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Limoges"
		population = 20000
		location = 419
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CHI
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Lyon"
		population = 20000
		location = 408
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CHM
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Tsaritsyn"
		population = 20000
		location = 458
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CMG
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Reims"
		population = 20000
		location = 376
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CNW
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Plymouth"
		population = 20000
		location = 250
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = COI
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Nizhniy Novgorod"
		population = 20000
		location = 272
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = COL
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Sable d'Olonnes"
		population = 20000
		location = 417
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CON
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Galway"
		population = 20000
		location = 231
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = COR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Bastia"
		population = 20000
		location = 398
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CRD
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 10
		#orthodox = -10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Sevilla"
		population = 20000
		location = 443
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CRE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Belgorod"
		population = 20000
		location = 450
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CRG
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Chernigov"
		population = 20000
		location = 294
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CRI
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Kherson"
		population = 20000
		location = 463
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CRO
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Zagreb"
		population = 20000
		location = 366
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CUM
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Bogutjar"
		population = 20000
		location = 451
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CYP
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Famagusta"
		population = 20000
		location = 484
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = CYR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Benghazi"
		population = 20000
		location = 741
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = DAH
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Messina"
		population = 20000
		location = 395
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = DAI
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Kaffa"
		population = 20000
		location = 464
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = DAK
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Kursk"
		population = 20000
		location = 286
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = DAM
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Lugansk"
		population = 20000
		location = 459
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = DAN
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "København"
		population = 20000
		location = 307
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = DAU
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Grenoble"
		population = 20000
		location = 407
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = DEL
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Ufa"
		population = 20000
		location = 453
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = DLH
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Tambov"
		population = 20000
		location = 447
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = DUL
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Sivas"
		population = 20000
		location = 474
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = EDE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Mosul"
		population = 20000
		location = 486
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = EGY
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Oslo"
		population = 20000
		location = 255
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = EIR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Nantes"
		population = 20000
		location = 416
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ENG
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "London"
		population = 20000
		location = 247
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ETH
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Rennes"
		population = 20000
		location = 414
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = FAT
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Bergen"
		population = 20000
		location = 256
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = FEZ
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Fez"
		population = 20000
		location = 733
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = FLA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Antwerpen"
		population = 20000
		location = 380
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = FPR
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Trondheim"
		population = 20000
		location = 258
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = FRC
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Vaagan"
		population = 20000
		location = 259
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = FRI
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Groningen"
		population = 20000
		location = 337
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = FUC
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Biskra"
		population = 20000
		location = 735
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = GEL
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Arnhem"
		population = 20000
		location = 338
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = GEN
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Genova"
		population = 20000
		location = 403
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = GEO
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Tblisi"
		population = 20000
		location = 470
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = GOT
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Visby"
		population = 20000
		location = 308
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = GRA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 10
		#orthodox = -10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Grenada"
		population = 20000
		location = 444
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = GRE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -5
		#orthodox = 10
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Athene"
		population = 20000
		location = 359
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = GUJ
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Gävle"
		population = 20000
		location = 1469
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = HAI
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Corfu"
		population = 20000
		location = 820
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = HAM
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Kiruna"
		population = 20000
		location = 260
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = HAN
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Hannover"
		population = 20000
		location = 310
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = HAU
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Brussels"
		population = 20000
		location = 378
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = HEI
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Vardø"
		population = 20000
		location = 261
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = HEL
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Zürich"
		population = 20000
		location = 1612
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = HES
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Kassel"
		population = 20000
		location = 333
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = HLL
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Amsterdam"
		population = 20000
		location = 339
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = HSA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Umeå"
		population = 20000
		location = 341
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = HUR
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Besancon"
		population = 20000
		location = 387
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = HYD
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Nevers"
		population = 20000
		location = 386
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ICE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Oran"
		population = 20000
		location = 734
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = INC
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Vasa"
		population = 20000
		location = 263
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = IRA
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Bagdad"
		population = 20000
		location = 489
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = IST
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Triest"
		population = 20000
		location = 368
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = JAI
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Östersund"
		population = 20000
		location = 381
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = JER
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Alexandretta"
		population = 20000
		location = 483
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = JUT
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Aalborg"
		population = 20000
		location = 309
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KAR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Larende"
		population = 20000
		location = 1611
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KAZ
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Iaroslav"
		population = 20000
		location = 446
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KHM
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Bristol"
		population = 20000
		location = 246
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KIE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Constantine"
		population = 20000
		location = 736
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KLE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Düsseldorf"
		population = 20000
		location = 343
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KOL
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Köln"
		population = 20000
		location = 344
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KON
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Lincoln"
		population = 20000
		location = 245
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KOR
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Tavastehus"
		population = 20000
		location = 264
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KRE
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Candia"
		population = 20000
		location = 480
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KRN
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Olofsborg"
		population = 20000
		location = 273
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KSH
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Danzig"
		population = 20000
		location = 301
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KUR
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Riga"
		population = 20000
		location = 283
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KUS
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Küstrin"
		population = 20000
		location = 313
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = KZK
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Canterbury"
		population = 20000
		location = 248
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LAN
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Lancaster"
		population = 20000
		location = 242
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LAP
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Inverness"
		population = 20000
		location = 236
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LAT
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Dorpat"
		population = 20000
		location = 282
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LEI
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Wexford"
		population = 20000
		location = 234
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LEO
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Salamanca"
		population = 20000
		location = 435
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LGD
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Wien"
		population = 20000
		location = 351
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LIT
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Vilnius"
		population = 20000
		location = 288
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LIV
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Viborg"
		population = 20000
		location = 265
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LOR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Nancy"
		population = 20000
		location = 375
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LOU
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Kexholm"
		population = 20000
		location = 266
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LUA
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Kola"
		population = 20000
		location = 262
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = LUX
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Luxemburg"
		population = 20000
		location = 377
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MAA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Guns"
		population = 20000
		location = 352
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MAG
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Magdeburg"
		population = 20000
		location = 311
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MAH
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Pilsen"
		population = 20000
		location = 330
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MAI
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Mainz"
		population = 20000
		location = 346
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MAL
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Valletta"
		population = 20000
		location = 819
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MAN
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Mantua"
		population = 20000
		location = 390
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MCH
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Newcastle"
		population = 20000
		location = 240
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MEA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Dublin"
		population = 20000
		location = 233
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MEC
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Lübeck"
		population = 20000
		location = 305
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MES
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Kalevala"
		population = 20000
		location = 1470
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MEX
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Kargopor"
		population = 20000
		location = 267
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MIN
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Narva"
		population = 20000
		location = 275
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MKS
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Aberdeen"
		population = 20000
		location = 237
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MLC
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -5
		#orthodox = 10
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Arkhangelsk"
		population = 20000
		location = 269
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MLL
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Palma"
		population = 20000
		location = 821
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MLO
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Milan"
		population = 20000
		location = 389
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MLW
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Edinburgh"
		population = 20000
		location = 238
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MOG
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Nish"
		population = 20000
		location = 363
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MOL
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -5
		#orthodox = 10
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Iasi"
		population = 20000
		location = 318
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MOR
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Marrakech"
		population = 20000
		location = 806
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MOS
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -5
		#orthodox = 10
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Moskva"
		population = 20000
		location = 270
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MSK
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Minsk"
		population = 20000
		location = 284
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MST
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Cork"
		population = 20000
		location = 235
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MTR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Krems"
		population = 20000
		location = 327
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MUN
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Münster"
		population = 20000
		location = 334
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MYA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Gniezno"
		population = 20000
		location = 300
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = MYS
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Poznan"
		population = 20000
		location = 303
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = NAF
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Uralsk"
		population = 20000
		location = 455
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = NAP
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Nàpoli"
		population = 20000
		location = 393
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = NAV
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Pamplona"
		population = 20000
		location = 428
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = NIP
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Brünn"
		population = 20000
		location = 315
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = NOG
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Karlsbad"
		population = 20000
		location = 329
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = NOR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Velikije Luki"
		population = 20000
		location = 280
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = NRM
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Caen"
		population = 20000
		location = 413
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = NVG
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Novgorod"
		population = 20000
		location = 274
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = OHI
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Calais"
		population = 20000
		location = 382
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = OLD
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Oldenburg"
		population = 20000
		location = 335
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = OMA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Thessaloniki"
		population = 20000
		location = 358
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ORI
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -0
	}
	city = {
		name = "Sarapol"
		population = 20000
		location = 456
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ORL
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Orleans"
		population = 20000
		location = 411
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PAM
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Baku"
		population = 20000
		location = 487
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
		}
} 

country = {
	tag = PAR
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Modena"
		population = 20000
		location = 402
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PEG
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Torino"
		population = 20000
		location = 404
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PER
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Konya"
		population = 20000
		location = 482
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PET
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Amman"
		population = 20000
		location = 495
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PEU
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Bône"
		population = 20000
		location = 738
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PFA
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Heidelberg"
		population = 20000
		location = 345
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PIC
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Amiens"
		population = 20000
		location = 383
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PIS
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Siena"
		population = 20000
		location = 400
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = POD
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Lublin"
		population = 20000
		location = 292
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = POI
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "La Rochelle"
		population = 20000
		location = 418
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = POK
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Vitebsk"
		population = 20000
		location = 281
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = POL
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Krakow"
		population = 20000
		location = 299
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = POM
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Stettin"
		population = 20000
		location = 302
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PRM
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Smyrna"
		population = 20000
		location = 478
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PRO
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Marseille"
		population = 20000
		location = 406
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PRT
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Porto"
		population = 20000
		location = 434
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PRU
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Königsberg"
		population = 20000
		location = 290
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PSK
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Pskow"
		population = 20000
		location = 277
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PUR
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Coventry"
		population = 20000
		location = 244
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = QAR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Nürnberg"
		population = 20000
		location = 348
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = QUE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Silistra"
		population = 20000
		location = 320
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = RAG
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Ragusa"
		population = 20000
		location = 362
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ROM
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Bologna"
		population = 20000
		location = 391
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ROY
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Rhodes"
		population = 20000
		location = 481
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = RYA
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -5
		#orthodox = 10
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Ryazan"
		population = 20000
		location = 448
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SAC
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Dresden"
		population = 20000
		location = 331
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SAR
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Cagliari"
		population = 20000
		location = 397
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SAV
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Chambéry"
		population = 20000
		location = 405
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SCO
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Glasgow"
		population = 20000
		location = 239
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SEI
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Graz"
		population = 20000
		location = 369
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SEL
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = shiite
		#catholic = 0
		#orthodox = 0
		#sunni = -10
		#shiite = 10
	}
	city = {
		name = "Hamadan"
		population = 20000
		location = 531
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SER
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Beograd"
		population = 20000
		location = 355
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SEV
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Sochi"
		population = 20000
		location = 469
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SHA
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Karlsburg"
		population = 20000
		location = 324
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SHL
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Hamburg"
		population = 20000
		location = 306
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SIB
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Ungvàr"
		population = 20000
		location = 317
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SIC
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Palermo"
		population = 20000
		location = 396
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SIE
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Hermannstadt"
		population = 20000
		location = 323
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SIL
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Breslau"
		population = 20000
		location = 314
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SKA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Lund"
		population = 20000
		location = 251
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SLO
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Kassa"
		population = 20000
		location = 316
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SLZ
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Salzburg"
		population = 20000
		location = 350
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SMO
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Smolensk"
		population = 20000
		location = 285
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SON
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Ochakov"
		population = 20000
		location = 296
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SPR
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Paris"
		population = 20000
		location = 385
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = STR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Straßburg"
		population = 20000
		location = 374
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = STT
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Stralsund"
		population = 20000
		location = 304
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SUD
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Khartoum"
		population = 20000
		location = 750
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SUZ
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Vladimir"
		population = 20000
		location = 271
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SWA
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Rome"
		population = 20000
		location = 399
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SWE
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Stockholm"
		population = 20000
		location = 254
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = SYR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Damascus"
		population = 20000
		location = 490
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TAN
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Tangiers"
		population = 20000
		location = 732
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TAU
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Preáburg"
		population = 20000
		location = 326
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TEK
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = -10
		#orthodox = 10
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Antalya"
		population = 20000
		location = 1610
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = THE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "El Alamein"
		population = 20000
		location = 742
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = THU
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Würzburg"
		population = 20000
		location = 347
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TIB
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Lwow"
		population = 20000
		location = 298
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TIM
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Asyut"
		population = 20000
		location = 743
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TOS
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Firenze"
		population = 20000
		location = 401
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TOU
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Montpellier"
		population = 20000
		location = 422
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TOX
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Assuan"
		population = 20000
		location = 747
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TRE
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Trapzon"
		population = 20000
		location = 475
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TRI
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Tripoli"
		population = 20000
		location = 740
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TUN
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Tunis"
		population = 20000
		location = 739
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TVE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Tver"
		population = 20000
		location = 278
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = TYR
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Innsbruck"
		population = 20000
		location = 371
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U01
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Lisbon"
		population = 20000
		location = 441
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U02
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Eger"
		population = 20000
		location = 325
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U03
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Bursa"
		population = 20000
		location = 477
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U06
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Tula"
		population = 20000
		location = 279
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U07
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Temeschburg"
		population = 20000
		location = 354
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U08
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Reval"
		population = 20000
		location = 276
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U10
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Mora"
		population = 20000
		location = 257
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U11
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Madrid"
		population = 20000
		location = 436
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U12
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Ancona"
		population = 20000
		location = 392
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U15
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Valencia"
		population = 20000
		location = 437
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U25
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Åbo"
		population = 20000
		location = 342
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U26
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -5
		#orthodox = 10
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Varna"
		population = 20000
		location = 321
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U29
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Zara"
		population = 20000
		location = 365
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U30
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Naxos"
		population = 20000
		location = 479
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U31
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Dongola"
		population = 20000
		location = 748
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U32
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Suakin"
		population = 20000
		location = 749
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U33
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Medina"
		population = 20000
		location = 497
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U34
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Beirut"
		population = 20000
		location = 491
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U35
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Acre"
		population = 20000
		location = 492
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U36
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Sulaymanieh"
		population = 20000
		location = 488
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U37
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = shiite
		#catholic = 0
		#orthodox = 0
		#sunni = -10
		#shiite = 10
	}
	city = {
		name = "Tabriz"
		population = 20000
		location = 530
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U38
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Rouen"
		population = 20000
		location = 384
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = U39
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Ismail"
		population = 20000
		location = 319
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = UKR
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = -10
		#orthodox = 10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Kiev"
		population = 20000
		location = 295
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ULS
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Belfast"
		population = 20000
		location = 232
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = USA
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Warszaw"
		population = 20000
		location = 291
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = UZB
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Czernowitz"
		population = 20000
		location = 297
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = WAL
	policy = {
		centralization = 4
		mercantilism = 8
	}
	religion = {
		type = orthodox
		#catholic = 0
		#orthodox = 10
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Bucuresti"
		population = 20000
		location = 322
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = VEN
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = 0
		#sunni = -10
		#shiite = -10
	}
	city = {
		name = "Venézia"
		population = 20000
		location = 370
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = VER
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Alexandria"
		population = 20000
		location = 744
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = VIE
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Damietta"
		population = 20000
		location = 745
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = VIJ
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Cairo"
		population = 20000
		location = 746
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = WLS
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Cardiff"
		population = 20000
		location = 243
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = VOL
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Brest Litovsk"
		population = 20000
		location = 293
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = WUR
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Stuttgart"
		population = 20000
		location = 372
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = XHO
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Akaba"
		population = 20000
		location = 494
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = YOR
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "York"
		population = 20000
		location = 241
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ZAN
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -10
		#sunni = 0
		#shiite = 0
	}
	city = {
		name = "Toledo"
		population = 20000
		location = 439
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ZAP
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Memel"
		population = 20000
		location = 289
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ZEE
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Vlissingen"
		population = 20000
		location = 340
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ZIM
	policy = {
		centralization = 6
		mercantilism = 8
	}
	religion = {
		type = catholic
		#catholic = 10
		#orthodox = -5
		#sunni = -5
		#shiite = -5
	}
	city = {
		name = "Portsmouth"
		population = 20000
		location = 249
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = ZUL
	policy = {
		centralization = 8
		mercantilism = 8
	}
	religion = {
		type = sunni
		#catholic = 0
		#orthodox = 0
		#sunni = 10
		#shiite = -10
	}
	city = {
		name = "Jerusalem"
		population = 20000
		location = 493
		fortress = { level = 2 }
		capital = yes
		bailiff = yes
	}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

country = {
	tag = PAP
	city = {
		name = "Kaigon City"
		population = 40000
		location = 814
		barrack = yes
		bailiff = yes
		cityrights = yes
		courthouse = yes
		fortress = { level = 6 }
		manufactory = luxury
		construction = luxury
		capital = yes
		}
	technology = {
		land = { level = 12 }
		naval = { level = 12 }
		trade = { level = 3 }
		infra = { level = 3 }
	}
}

