儿F 5dip
include = "Scenarios\Option_diplomats.inc"
九LSE
九NDIF

儿F 1000d
include = "Scenarios\Option_1000d.inc"
九LSE
九NDIF

儿F 100mp
include = "Scenarios\Option_manpower.inc"
九LSE
九NDIF

儿F Europeknown
include = "Scenarios\Option_knowneurope.inc"
九LSE
include = "Scenarios\Option_unknowneurope.inc"
九NDIF

儿F RandCoT
event = "Db\Events\COTevents.txt"
九LSE
include = "Scenarios\Option_cots.inc"
九NDIF

#儿F DPevents
#event = "Db\Events\DPsliders.txt"
#九LSE
#九NDIF

儿F BBAI
event = "Db\Events\AIevents1.txt"
九LSE
event = "Db\Events\AIevents2.txt"
九NDIF

儿F Reformation
include = "Scenarios\Option_reformation.inc"
九LSE
九NDIF
