# Events for the reformation mod - by Alun
event = "Db\Reformation\RNGC_Main.txt"
event = "Db\Reformation\Protestant_Britain.txt"
event = "Db\Reformation\Protestant_Lowlands.txt"
event = "Db\Reformation\Protestant_Germany.txt"
event = "Db\Reformation\Protestant_Scandinavia.txt"
event = "Db\Reformation\Protestant_Other.txt"
event = "Db\Reformation\Reformed_Britain.txt"
event = "Db\Reformation\Reformed_France.txt"
event = "Db\Reformation\Reformed_Lowlands.txt"
event = "Db\Reformation\Reformed_Germany.txt"
event = "Db\Reformation\Reformed_Other.txt"
event = "Db\Reformation\RNGC_Protestant_Britain.txt"
event = "Db\Reformation\RNGC_Protestant_Lowlands.txt"
event = "Db\Reformation\RNGC_Protestant_Germany.txt"
event = "Db\Reformation\RNGC_Protestant_Scandinavia.txt"
event = "Db\Reformation\RNGC_Protestant_Other.txt"
event = "Db\Reformation\RNGC_Reformed_Britain.txt"
event = "Db\Reformation\RNGC_Reformed_France.txt"
event = "Db\Reformation\RNGC_Reformed_Lowlands.txt"
event = "Db\Reformation\RNGC_Reformed_Germany.txt"
event = "Db\Reformation\RNGC_Reformed_Other.txt"

province = { id = 236 religion = catholic } 
province = { id = 237 religion = catholic } 
province = { id = 238 religion = catholic } 
province = { id = 239 religion = catholic } 
province = { id = 240 religion = catholic } 
province = { id = 242 religion = catholic } 
province = { id = 244 religion = catholic } 
province = { id = 245 religion = catholic } 
province = { id = 246 religion = catholic } 
province = { id = 247 religion = catholic } 
province = { id = 248 religion = catholic } 
province = { id = 249 religion = catholic } 
province = { id = 250 religion = catholic } 
province = { id = 251 religion = catholic } 
province = { id = 252 religion = catholic } 
province = { id = 253 religion = catholic } 
province = { id = 254 religion = catholic } 
province = { id = 255 religion = catholic } 
province = { id = 256 religion = catholic } 
province = { id = 257 religion = catholic } 
province = { id = 258 religion = catholic } 
province = { id = 259 religion = catholic } 
province = { id = 260 religion = catholic } 
province = { id = 261 religion = catholic } 
province = { id = 263 religion = catholic } 
province = { id = 264 religion = catholic } 
province = { id = 265 religion = catholic } 
province = { id = 266 religion = catholic } 
province = { id = 273 religion = catholic } 
province = { id = 276 religion = catholic } 
province = { id = 282 religion = catholic } 
province = { id = 283 religion = catholic } 
province = { id = 289 religion = catholic } 
province = { id = 290 religion = catholic } 
province = { id = 301 religion = catholic } 
province = { id = 302 religion = catholic } 
province = { id = 303 religion = catholic } 
province = { id = 304 religion = catholic } 
province = { id = 305 religion = catholic } 
province = { id = 306 religion = catholic } 
province = { id = 307 religion = catholic } 
province = { id = 308 religion = catholic } 
province = { id = 309 religion = catholic } 
province = { id = 310 religion = catholic } 
province = { id = 311 religion = catholic } 
province = { id = 312 religion = catholic } 
province = { id = 313 religion = catholic } 
province = { id = 314 religion = catholic } 
province = { id = 323 religion = catholic } 
province = { id = 324 religion = catholic } 
province = { id = 325 religion = catholic } 
province = { id = 328 religion = catholic } 
province = { id = 330 religion = catholic } 
province = { id = 331 religion = catholic } 
province = { id = 332 religion = catholic } 
province = { id = 333 religion = catholic } 
province = { id = 335 religion = catholic } 
province = { id = 336 religion = catholic } 
province = { id = 337 religion = catholic } 
province = { id = 338 religion = catholic } 
province = { id = 339 religion = catholic } 
province = { id = 340 religion = catholic } 
province = { id = 341 religion = catholic } 
province = { id = 342 religion = catholic } 
province = { id = 345 religion = catholic } 
province = { id = 346 religion = catholic } 
province = { id = 347 religion = catholic } 
province = { id = 354 religion = catholic } 
province = { id = 372 religion = catholic } 
province = { id = 380 religion = catholic } 
province = { id = 381 religion = catholic } 
province = { id = 388 religion = catholic } 
province = { id = 407 religion = catholic } 
province = { id = 412 religion = catholic } 
province = { id = 418 religion = catholic } 
province = { id = 419 religion = catholic } 
province = { id = 421 religion = catholic } 
province = { id = 422 religion = catholic } 
province = { id = 423 religion = catholic } 
province = { id = 425 religion = catholic } 
province = { id = 1469 religion = catholic } 
province = { id = 1612 religion = catholic } 
